In [1]:
import pandas as pd
import itertools

Data from NIH data

https://grant-witness.us/nih-data.html

https://hsph.harvard.edu/news/creating-a-trusted-database-of-federal-research-funding-cuts/

In [2]:
df = pd.read_csv('./data/nih_v3_terminations.csv')

In [3]:
df

,grant_id,subgrant_id,core_award_number,full_award_number,activity_code,institute_code,subproject_id,current_status,detailed_status,title,...,opportunity_title,opportunity_url,current_total_obligated,post_termination_deobligation,award_value,award_outlaid,award_remaining,reporter_url,usaspending_url,taggs_url
0,AA007459,NaN,T32AA007459,5T32AA007459-40,T32,AA,NaN,Restored,Unfrozen (confirmed),Alcohol Intervention Treatment Outcome Researc...,...,Ruth L. Kirschstein National Research Service ...,https://grants.nih.gov/grants/guide/pa-files/P...,8903933.00,NaN,8903933.00,2021558.65,6882374.35,https://reporter.nih.gov/project-details/11098673,https://www.usaspending.gov/award/ASST_NON_T32...,NaN
1,AA019072,NaN,P01AA019072,5P01AA019072-15,P01,AA,NaN,Restored,Unfrozen (confirmed),Addressing alcohol misuse in HIV prevention an...,...,Alcohol-HIV/AIDS Program Project (P01 Clinical...,https://grants.nih.gov/grants/guide/pa-files/R...,19658333.00,NaN,19658333.00,4853500.60,14804832.40,https://reporter.nih.gov/project-details/10879090,https://www.usaspending.gov/award/ASST_NON_P01...,NaN
2,AA024434,NaN,R01AA024434,5R01AA024434-10,R01,AA,NaN,Restored,Unfrozen (confirmed),Notch-dependent microcircuit regulation of alc...,...,Research Project Grant (Parent R01 Clinical Tr...,https://grants.nih.gov/grants/guide/pa-files/P...,3903456.00,NaN,3903456.00,1545133.43,2358322.57,https://reporter.nih.gov/project-details/11137591,https://www.usaspending.gov/award/ASST_NON_R01...,NaN
3,AA026186,NaN,R01AA026186,5R01AA026186-10,R01,AA,NaN,Restored,Unfrozen (confirmed),Endocannabinoid Mechanisms in the Pathophysiol...,...,NIH Research Project Grant (Parent R01 Clinica...,https://grants.nih.gov/grants/guide/pa-files/P...,3188075.26,NaN,3188075.26,1317401.98,1870673.28,https://reporter.nih.gov/project-details/11324549,https://www.usaspending.gov/award/ASST_NON_R01...,NaN
4,AA026297,NaN,R01AA026297,5R01AA026297-09,R01,AA,NaN,Restored,Unfrozen (confirmed),Aldh2 and epithelial homeostasis and pathobiology,...,NIH Research Project Grant (Parent R01 Clinica...,https://grants.nih.gov/grants/guide/pa-files/P...,2928362.18,NaN,2928362.18,1226006.45,1702355.73,https://reporter.nih.gov/project-details/11381708,https://www.usaspending.gov/award/ASST_NON_R01...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5516,TW012677,NaN,R01TW012677,1R01TW012677-01A1,R01,TW,NaN,Restored,Unfrozen (confirmed),Engaging Vulnerable Women in HIV Prevention an...,...,Interventions for Stigma Reduction to Improve ...,https://grants.nih.gov/grants/guide/pa-files/P...,173197.00,NaN,173197.00,169209.31,3987.69,https://reporter.nih.gov/project-details/11002762,https://www.usaspending.gov/award/ASST_NON_R01...,NaN
5517,TW012808,NaN,P20TW012808,5P20TW012808-02,P20,TW,NaN,Restored,Reinstated (confirmed),The Anga Center for Community Health and Well-...,...,Exploratory Grants for Climate Change and Heal...,https://grants.nih.gov/grants/guide/pa-files/R...,2109010.00,NaN,2109010.00,60720.12,2048289.88,https://reporter.nih.gov/project-details/11397208,https://www.usaspending.gov/award/ASST_NON_P20...,NaN
5518,TW012850,NaN,K43TW012850,5K43TW012850-02,K43,TW,NaN,Restored,Reinstated (unconfirmed),Adapting an evidence-based intervention to imp...,...,Emerging Global Leader Award (K43 Independent ...,https://grants.nih.gov/grants/guide/pa-files/P...,134406.00,NaN,134406.00,66427.00,67979.00,https://reporter.nih.gov/project-details/11374076,https://www.usaspending.gov/award/ASST_NON_K43...,NaN
5519,TW012904,NaN,R01TW012904,5R01TW012904-02,R01,TW,NaN,Restored,Reinstated (confirmed),Kabawil: Adapting an Intervention to Reduce In...,...,Interventions for Stigma Reduction to Improve ...,https://grants.nih.gov/grants/guide/pa-files/P...,432176.00,NaN,432176.00,220077.98,212098.02,https://reporter.nih.gov/project-details/11362792,https://www.usaspending.gov/award/ASST_NON_R01...,NaN
5520,TW013028,NaN,P20TW013028,5P20TW013028-02,P20,TW,NaN,Restored,Reinstated (confirmed),Center for Effective and Accessible Research-b...,...,Exploratory Grants for Climate Change and Heal...,https://grants.nih.gov/grants/guide/pa-files/R...,2525164.00,NaN,2525164.00,845984.22,1679179.78,https://reporter.nih.gov/project-details/11193870,https://www.usaspending.gov/award/ASST_NON_P20...,NaN

In [4]:
df.columns

Index(['grant_id', 'subgrant_id', 'core_award_number', 'full_award_number',
       'activity_code', 'institute_code', 'subproject_id', 'current_status',
       'detailed_status', 'title', 'latest_disruption_date',
       'latest_restoration_date', 'first_termination_date',
       'latest_termination_date', 'first_reinstatement_date',
       'latest_reinstatement_date', 'frozen_date', 'unfrozen_date',
       'latest_outlay', 'latest_renewal', 'latest_budget_end', 'project_start',
       'project_end', 'event_history', 'signals', 'has_been_terminated',
       'has_been_reinstated', 'has_been_frozen', 'has_been_unfrozen',
       'has_been_delayed', 'study_section', 'abstract',
       'public_health_relevance', 'terms', 'spending_categories',
       'categories_predicted', 'funding_category', 'program_office',
       'nih_activity', 'flagged_words', 'org_name', 'org_state', 'org_city',
       'org_country', 'org_type', 'org_traits', 'pct_ugrad_pellgrant',
       'pct_ugrad_fedloan', 'department_type', 'congressional_district',
       'cfda_number', 'cfda_title', 'opportunity_number', 'opportunity_title',
       'opportunity_url', 'current_total_obligated',
       'post_termination_deobligation', 'award_value', 'award_outlaid',
       'award_remaining', 'reporter_url', 'usaspending_url', 'taggs_url'],
      dtype='object')

In [5]:
flagged_new_all = pd.Series(df['flagged_words'].tolist()).dropna().tolist()
flagged_new = set(list(itertools.chain.from_iterable([i.split(', ') for i in flagged_new_all])))


len(flagged_new)

167

From https://pen.org/banned-words-list/

In [6]:
# banned_words = """abortion accessibility Accessible activism activists advocacy advocate advocates affirmative action affirmative action programs affirming care affordable home affordable housing agricultural water agrivoltaics air pollution all-inclusive allyship alternative energy anti-racism antiracist asexual assigned at birth assigned female at birth assigned male at birth at risk autism aviation fuel barrier barriers belong bias biased Biased toward biases Biases towards bioenergy biofuel biogas biologically female biologically male biomethane bipoc bisexual Black black and latinx breastfeed + people breastfeed + person Cancer Moonshot carbon emissions mitigation carbon footprint carbon markets carbon pricing carbon sequestration CEC changing climate chestfeed + people chestfeed + person clean energy clean fuel clean power clean water climate climate accountability climate change climate consulting climate crisis climate model climate models climate resilience climate risk climate science climate smart agriculture climate smart forestry climate variability climate-change climatesmart commercial sex worker community community diversity community equity confirmation bias contaminants of environmental concern continuum Covid-19 critical race theory cultural competence cultural differences cultural heritage Cultural relevance cultural sensitivity culturally appropriate culturally responsive decarbonization definition DEI DEIA DEIAB DEIJ diesel dietary guidelines/ultraprocessed foods dirty energy disabilities disability disabled disadvantaged discriminated discrimination discriminatory discussion of federal policies disparity diverse diverse backgrounds diverse communities diverse community diverse group diverse groups diversified diversify diversifying diversity diversity and inclusion diversity in the workplace diversity, equity, and inclusion diversity/equity efforts EEJ EJ elderly electric vehicle emissions energy conversion energy transition enhance the diversity enhancing diversity entitlement environmental justice environmental quality equal opportunity equality equitable equitableness equity ethnicity evidence-based excluded exclusion expression female females feminism fetus field drainage fluoride fostering inclusivity fuel cell gay GBV gender gender based gender based violence gender diversity gender dysphoria gender expression gender identity gender ideology gender nonconformity gender transition gender-affirming care gendered genders geothermal GHG emission GHG modeling GHG monitoring global warming green green infrastructure greenhouse gas emission groundwater pollution Gulf of Mexico H5N1/bird flu hate hate speech health disparity health equity hispanic hispanic minority historically housing affordability housing efficiency hydrogen vehicle identity ideology immigrants implicit bias implicit biases inclusion inclusive inclusive leadership inclusiveness inclusivity Increase diversity increase the diversity indigenous indigenous community/ people inequalities inequality inequitable inequities injustice institutional integration intersectional intersectionality intersex issues concerning pending legislation justice40 key groups key people key populations Latinx lesbian lgbt LGBTQ low-emission vehicle low-income housing male dominated marginalize marginalized marijuana measles membrane filtration men who have sex with men mental health methane emissions microplastics migrant minorities minority minority serving institution most risk MSI msm multicultural Mx Native American NCI budget net-zero non-binary nonbinary noncitizen non-conforming nonpoint source pollution nuclear energy nuclear power obesity opioids oppression oppressive orientation pansexual PCB peanut allergies people + uterus people of color people-centered care person-centered person-centered care PFAS PFOA photovoltaic polarization political pollution pollution abatement pollution remediation prefabricated housing pregnant people pregnant person pregnant persons prejudice privilege privileges promote promote diversity promoting diversity pronoun pronouns prostitute pyrolysis QT queer race race and ethnicity racial racial diversity racial identity racial inequality racial justice racially racism runoff rural water safe drinking water science-based sediment remediation segregation self-assessed sense of belonging sex sexual preferences sexuality social justice social vulnerability socio cultural socio economic sociocultural socioeconomic status soil pollution solar energy solar power special populations stem cell or fetal tissue research stereotype stereotypes subsidized housing sustainability/sustainable sustainable construction systemic systemically tax breaks tax credits tax subsidies they/them tile drainage topics of federal investigations topics that have received recent attention from Congress topics that have received widespread or critical media attention trans transexual transexualism transexuals transgender transgender military personnel transgender people transitional housing trauma traumatic tribal two-spirit unconscious bias under appreciated under represented under served underprivileged underrepresentation underrepresented underserved understudied undervalued vaccines victim victims vulnerable vulnerable populations water collection water conservation water distribution water efficiency water management water pollution water quality water storage water treatment white privilege wind power woman women women and underrepresented women in leadership""".split()

From Sen. Cruz's list (official)

In [7]:

statusbanstring = '''
ACTIVISM; ACTIVIST; ACTIVISTS; ADVOCACY; ADVOCATE; ADVOCATES; AFFIRMATIVE ACTION; BIAS TOWARD;
 BIAS TOWARDS; BIASED; BIASED TOWARD; BIASED TOWARDS; BIASES; BIASES TOWARD; BIASES TOWARDS; DE
COLONIZATION; DE COLONIZE; DE COLONIZED; DE COLONIZING; DE SEGREGATE; DE SEGREGATED; DE
SEGREGATES; DE SEGREGATION; DECOLONIZATION; DECOLONIZE; DECOLONIZED; DECOLONIZING;
DESEGREGATE; DESEGREGATED; DESEGREGATES; DESEGREGATION; DISCRIMINATE; DISCRIMINATED;
DISCRIMINATION; DISCRIMINATORY; DIVISIVENESS; EXCLUDED; EXCLUSION; EXCLUSIVE; FEEL SEEN AND HEARD;
HATE SPEECH; HISTORICALLY; IMPLICIT BIAS; IMPLICIT BIASES; INJUSTICE; INJUSTICES; INSTITUTIONAL;
INSTITUTIONALIZE; INSTITUTIONALIZED; INSTITUTIONALLY; INTERGENERATIONAL TRAUMA; INTERSECTIONAL;
INTERSECTIONALITY; MARGINALIZATION; MARGINALIZE; MARGINALIZED; MICRO AGGRESSION; MICRO
AGGRESSIONS; MICRO AGGRESSIVE; MICRO AGGRESSIVENESS; MICROAGGRESSION; MICROAGGRESSIONS;
MICROAGGRESSIVE; MICROAGGRESSIVENESS; MINORITIES; MINORITY; OPPRESSED; OPPRESSIVE;
OPPRESSIVENESS; OPPRESSION; POLARIZATION; POLARIZE; POLITICIZATION; POLITICIZE; POLITICAL; PREJUDICE;
PREJUDICES; PRIVILEGE; PRIVILEGED; PRIVILEGES; REPARATION; REPARATIONS; SEGREGATED; SEGREGATION;
SOCIO ECONOMIC; SOCIOECONOMIC; STATUS; STATUSES; STEREOTYPE; STEREOTYPES; STEREOTYPICAL;
STEREOTYPING; SYSTEM OF OPPRESSION; SYSTEMATIC OPPRESSION; SYSTEMATICALLY OPPRESSED; SYSTEMIC;
SYSTEMIC OPPRESSION; SYSTEMICAL; SYSTEMICALLY; SYSTEMICALLY OPPRESSED; SYSTEMS OF OPPRESSION;
SYSTEMS OF POWER; TRAUMA; TRAUMATIC; UNDER APPRECIATED; UNDER APPRECIATION; UNDER PRIVILEGE;
UNDER PRIVILEGED; UNDER REPRESENTATION; UNDER REPRESENTED; UNDER SERVED; UNDER SERVING; UNDER
VALUED; UNDER VALUING; UNDERAPPRECIATED; UNDERAPPRECIATION; UNDERPRIVILEGE; UNDERPRIVILEGED;
UNDERREPRESENTATION; UNDERREPRESENTED; UNDERSERVED; UNDERSERVING; UNDERVALUED; UNDERVALUING;
UNJUST; VICTIM; VICTIMHOOD; VICTIMIZED; VICTIMS; VOICES ARE ACKNOWLEDGED; VOICES HEARD; VOICES
MATTER; UNEQUAL OPPORTUNITIES; UNEQUAL OPPORTUNITY; SAFE SPACE; SAFE SPACES; SENSE OF
BELONGING; SENSE OF BELONGINGNESS; WELCOMING ENVIRONMENT; BARRIER; BARRIERS; DISABILITIES;
DISABILITY; ALLY; ALLYSHIP.
'''

socialbanstring = '''
ADVANCE DIVERSITY; ADVANCE INCLUSIVITY; ADVANCE THE DIVERSITY; ADVANCING DIVERSITY; ADVANCING 
INCLUSIVE; ALLIANCE FOR DIVERSITY; BACKGROUND INCLUSIVITY; BI CULTURAL; BICULTURAL; BLACK CULTURAL;
BLACK CULTURE; BLACK CULTURES; BROADEN DIVERSITY; BROADEN THE DIVERSITY; COMMITMENT TO DIVERSITY;
COMMUNITY DIVERSITY; COMMUNITY EQUITY; COMMUNITY INCLUSIVITY; CULTURAL ACTIVISM; CULTURAL
ACTIVIST; CULTURAL ACTIVISTS; CULTURAL ADVOCACY; CULTURAL ADVOCATE; CULTURAL AND ETHNIC;
CULTURAL AND RACIAL; CULTURAL APPROPRIATION; CULTURAL APPROPRIATIONS; CULTURAL BIAS; CULTURAL
COMPETENCY; CULTURAL CONNECTIONS; CULTURAL DIFFERENCES; CULTURAL HERITAGE; CULTURAL HUMILITY;
CULTURAL INEQUALITIES; CULTURAL INEQUALITY; CULTURAL INEQUITIES; CULTURAL INEQUITY; CULTURAL
INJUSTICE; CULTURAL INJUSTICES; CULTURAL JUSTICE; CULTURAL RELEVANCE; CULTURAL SEGREGATION;
CULTURALLY ATTUNED; CULTURALLY BIASED; CULTURALLY RESPONSIVE; CULTURALLY SENSITIVE; CULTURALLY
SUSTAINABLE; CULTURALLY SUSTAINING; CULTURE AND ETHNICITY; CULTURE AND RACE; CULTURES AND
ETHNICITIES; CULTURES AND RACES; DEI; DEIJ; DIVERSE BACKGROUND; DIVERSE BACKGROUNDS; DIVERSE
COMMUNITIES; DIVERSE COMMUNITY; DIVERSE GROUP; DIVERSE GROUPS; DIVERSE INDIVIDUAL; DIVERSE
INDIVIDUALS; DIVERSE STATUS; DIVERSE STATUSES; DIVERSE VOICES; DIVERSIFIED; DIVERSIFY; DIVERSIFYING;
DIVERSITY AND EQUITY; DIVERSITY AND INCLUSION; DIVERSITY AND INCLUSIVITY; DIVERSITY AWARENESS;
DIVERSITY EQUITY; EMPHASIS ON DIVERSITY; EMPHASIZE DIVERSITY; EMPHASIZING DIVERSITY; ENCOURAGE
DIVERSITY; ENCOURAGING DIVERSITY; ENHANCE DIVERSITY; ENHANCE THE DIVERSITY; ENHANCING DIVERSITY;
EQUAL OPPORTUNITIES; EQUAL OPPORTUNITY; EQUALITIES; EQUALITY; EQUITABLE; EQUITABLE AND INCLUSIVE;
EQUITIES; EQUITY; ETHNIC AND CULTURAL; ETHNIC CULTURAL; ETHNIC CULTURE; ETHNIC CULTURES; ETHNIC
DIVERSITY; ETHNIC EQUITY; ETHNICITIES AND CULTURES; ETHNICITY AND CULTURE; FOSTER DIVERSITY;
FOSTERING DIVERSITY; FOSTERING INCLUSIVE; FOSTERING INCLUSIVITY; FOSTERING THE DIVERSITY; GROUP
EQUITY; GROUP INCLUSIVITY; HISPANIC CULTURAL; HISPANIC CULTURE; HISPANIC CULTURES; INCLUSION;
INCLUSIVE; INCLUSIVE LANGUAGE; INCLUSIVENESS; INCLUSIVITY; INCLUSIVITY AND DIVERSITY; INCREASE DIVERSITY;
INCREASE THE DIVERSITY; INCREASES DIVERSITY; INCREASES THE DIVERSITY; INCREASING DIVERSITY; INCREASING
THE DIVERSITY; INDIGENOUS CULTURAL; INDIGENOUS CULTURE; INDIGENOUS CULTURES; INEQUALITIES;
INEQUALITY; INEQUITABLE; INEQUITIES; INEQUITY; INTER CULTURAL; INTER CULTURALLY; INTERCULTURAL;
INTERCULTURALLY; LACK OF DIVERSITY; LATINX CULTURAL; LATINX CULTURE; LATINX CULTURES; MULTI CULTURAL;
MULTI CULTURALLY; MULTICULTURAL; MULTICULTURALLY; PROMOTE DIVERSITY; PROMOTING DIVERSITY;
SEGREGATED CULTURES; SOCIAL ACTIVISM; SOCIAL ACTIVIST; SOCIAL ACTIVISTS; SOCIAL ADVOCACY; SOCIAL
ADVOCATE; SOCIAL BIAS; SOCIAL BIASES; SOCIAL INEQUALITIES; SOCIAL INEQUALITY; SOCIAL INEQUITIES;
SOCIAL INEQUITY; SOCIAL INJUSTICE; SOCIAL INJUSTICES; SOCIAL JUSTICE; SOCIAL JUSTICE ACTIVISM; SOCIAL
JUSTICE ADVOCACY; SOCIAL JUSTICE ADVOCATE; SOCIALLY BIASED; SOCIO CULTURAL; SOCIO CULTURALLY;
SOCIOCULTURAL; SOCIOCULTURALLY; STRUCTURAL INEQUALITY; STRUCTURAL INEQUITY; SUPPORT DIVERSITY;
SUPPORTING DIVERSITY; TRANS CULTURAL; TRANSCULTURAL; SOCIALLY RELEVANT; CULTURALLY RELEVANT
'''

genderbanstring='''
BIGOT; BIGOTRY; BLACK FEMALE; BLACK FEMALES; BLACK MALE; BLACK MALES; BLACK MEN; BLACK WOMEN;
CISGENDER; CISNORMATIVE; CISNORMATIVITY; COLORED FEMALE; COLORED FEMALES; COLORED MALE;
COLORED MALES; COLORED MEN; COLORED WOMEN; FEMALE; FEMALE VOICES; FEMALES; FEMININITY;
FEMINISM; FEMINIST; FEMINISTIC; FLUID IDENTITY; GENDER; GENDER ACCEPTANCE; GENDER AFFIRMATION;
GENDER AFFIRMING; GENDER AND SEXUAL; GENDER APPRECIATION; GENDER BASED; GENDER BINARY; GENDER
DISCRIMINATION; GENDER DISPARITIES; GENDER DISPARITY; GENDER DIVERSITY; GENDER DYSMORPHIA; GENDER
DYSPHORIA; GENDER FLUID; GENDER FLUIDITY; GENDER IDENTITY; GENDER IDEOLOGY; GENDER INCLUSIVE;
GENDER INCLUSIVITY; GENDER MARGINALIZED; GENDER MINORITIES; GENDER MINORITY; GENDER NEURAL;
GENDER NON BINARY; GENDER NON CONFORMING; GENDER NONBINARY; GENDER NONCONFORMING;
GENDER OPPRESSION; GENDER PREFERENCE; GENDER PREFERENCES; GENDER SPECTRUM; GENDER
STEREOTYPES; GENDER TRANSITION; GENDER TRANSITIONING; GENDER TYPICAL; GENDERS; HETEROSEXUAL;
HISPANIC FEMALE; HISPANIC FEMALES; HISPANIC MALE; HISPANIC MALES; HISPANIC MEN; HISPANIC WOMEN;
HISTORICALLY MALE; INDIGENOUS FEMALE; INDIGENOUS FEMALES; INDIGENOUS MALE; INDIGENOUS MALES;
INDIGENOUS MEN; INDIGENOUS WOMEN; INTERSECTIONAL FEMINISM; LATINA FEMALE; LATINA FEMALES; LATINA
MALE; LATINA MALES; LATINA MEN; LATINA WOMEN; LATINX FEMALE; LATINX FEMALES; LATINX MALE; LATINX
MALES; LATINX MEN; LATINX WOMEN; LGBT; LGBTQ; LGBTQ+; LGBTQIA; MALE DOMINANT; MALE
DOMINATED; MASCULINE; MASCULINITY; MIS GENDER; MISGENDER; MISOGYNISTIC; MISOGYNY; NON BINARY;
NON BINARY GENDER; NON CONFORMING GENDER; NONBINARY; NONBINARY GENDER; NONCONFORMING
GENDER; OPPRESSED GENDER; OPPRESSED GENDERS; OPPRESSED SEXUALITIES; PANSEXUAL; PREDOMINATELY
MALE; PREFERRED GENDER; PREFERRED IDENTITY; PREFERRED SEX; PRIMARILY MALE; PRONOUN; PRONOUNS;
QUEER THEORY; SELF IDENTIFY; SEX CHANGE; SEX PREFERENCE; SEX TRANSITION; SEXISM; SEXIST; SEXUAL
DISCRIMINATION; SEXUAL DISPARITIES; SEXUAL DISPARITY; SEXUAL IDENTITY; SEXUAL MINORITIES; SEXUAL
MINORITY; SEXUAL PREFERENCE; SEXUAL PREFERENCES; SEXUALITIES; SEXUALITY; STRAIGHT WHITE; TOXIC
MASCULINITY; TRANSGENDER; TRANSGENDERISM; TRANSITIONING GENDER; TRANSITIONING SEX; TRANSJUSTICE;
TRANSPHOBIA; TRANSPHOBIC; UNDERREPRESENTED GENDER; VOICES OF WOMEN; WHITE FEMALE; WHITE
FEMALES; WHITE MALE; WHITE MALES; WHITE MEN; WHITE WOMEN; WOMEN; WOMEN AND GENDER;
WOMEN AND UNDERREPRESENTED; WOMENUNDERREPRESENTED
'''
racebanstring='''
ANTI BLACK; ANTI BLACK RACISM; ANTI RACISM; ANTI RACIST; ANTI WHITE; ANTIBLACK; ANTIBLACK RACISM;
ANTIRACISM; ANTIRACIST; ANTIWHITE; BIPOC; BIPOCX; BLACK AND LATINX; BLACK COMMUNITIES; BLACK
COMMUNITY; BLACK INDIGENOUS AND LATINX; BLACK INDIGENOUS AND OTHER; BLACK INDIGENOUS LATINX;
BLACK INDIGENOUS OTHER; BLACK INDIVIDUAL; BLACK INDIVIDUALS; BLACK INTELLECTUALISM; BLACK LIVES
MATTER; BLACK MINORITIES; BLACK MINORITY; BLACK PEOPLE; BLACK PERSON; BLACK THOUGHT; BLACK
VOICES; BLACKNESS; COLORED COMMUNITIES; COLORED COMMUNITY; COLORED INDIVIDUAL; COLORED
INDIVIDUALS; COLORED MINORITIES; COLORED MINORITY; COLORED PEOPLE; COLORED PERSON; COLORED
VOICES; CRITICAL RACE THEORY; ETHNIC AND RACIAL; ETHNIC BIAS; ETHNIC COMMUNITIES; ETHNIC
COMMUNITY; ETHNIC IDENTITIES; ETHNIC IDENTITY; ETHNIC INDIVIDUAL; ETHNIC INDIVIDUALS; ETHNIC
MINORITIES; ETHNIC MINORITY; ETHNIC PEOPLE; ETHNIC PERSON; ETHNIC RACISM; ETHNIC SEGREGATION;
ETHNIC VOICES; ETHNICAL RACISM; ETHNICITIES AND RACES; ETHNICITY; ETHNICITY AND RACE; HISPANIC
COMMUNITIES; HISPANIC COMMUNITY; HISPANIC INDIVIDUAL; HISPANIC INDIVIDUALS; HISPANIC MINORITIES;
HISPANIC MINORITY; HISPANIC PEOPLE; HISPANIC PERSON; HISPANIC VOICES; HISTORICAL RACISM;
HISTORICALLY RACIST; HISTORICALLY WHITE; INDIGENOUS COMMUNITIES; INDIGENOUS COMMUNITY;
INDIGENOUS INDIVIDUAL; INDIGENOUS INDIVIDUALS; INDIGENOUS MINORITIES; INDIGENOUS MINORITY;
INDIGENOUS PEOPLE; INDIGENOUS PERSON; INDIGENOUS VOICES; INSTITUTIONAL RACISM; INSTITUTIONALIZED
RACISM; INSTITUTIONALLY RACIST; INTER RACIAL; INTER RACIALLY; INTERRACIAL; INTERRACIALLY; LATINA
COMMUNITIES; LATINA COMMUNITY; LATINA INDIVIDUAL; LATINA INDIVIDUALS; LATINA MINORITIES; LATINA
MINORITY; LATINA PEOPLE; LATINA PERSON; LATINA VOICES; LATINX COMMUNITIES; LATINX COMMUNITY;
LATINX INDIVIDUAL; LATINX INDIVIDUALS; LATINX MINORITIES; LATINX MINORITY; LATINX PEOPLE; LATINX
PERSON; LATINX VOICES; MULTI ETHNIC; MULTI ETHNICALLY; MULTIETHNIC; MULTIETHNICALLY; NON BLACK;
NON WHITE; NONBLACK; NONWHITE; PEOPLE OF COLOR; POC; POCX; PREDOMINATELY WHITE; PRIMARILY
WHITE; PRIVILEGED WHITE; PRO BLACK; PRO WHITE; PROBLACK; PROWHITE; RACE AND CULTURE; RACE AND
ETHNICITY; RACE BASED; RACEBASED; RACES AND CULTURES; RACES AND ETHNICITIES; RACIAL; RACIAL AND
CULTURAL; RACIAL AND ETHNIC; RACIAL BIAS; RACIAL BIASES; RACIAL DISPARITIES; RACIAL DISPARITY; RACIAL
DIVERSITY; RACIAL IDENTITY; RACIAL INEQUALITIES; RACIAL INEQUALITY; RACIAL INEQUITIES; RACIAL INEQUITY;
RACIAL INJUSTICE; RACIAL INJUSTICES; RACIAL JUSTICE; RACIAL MINORITIES; RACIAL MINORITY; RACIAL
OPPRESSION; RACIAL PREJUDICE; RACIAL PREJUDICES; RACIAL SEGREGATION; RACIAL SOCIALIZATION; RACIAL
SOLIDARITY; RACIAL STEREOTYPES; RACIAL VIOLENCE; RACIALLY; RACIALLY AND CULTURALLY; RACIALLY BIAS;
RACIALLY BIASED; RACIALLY OPPRESSED; RACISM; RACIST; SEGREGATED ETHNICITIES; SEGREGATED ETHNICITY;
SEGREGATED RACE; SEGREGATED RACES; STRUCTURAL RACISM; STRUCTURALLY RACIST; SYSTEMIC RACISM;
SYSTEMICALLY RACIST; TOKENISTIC; TOKENSIM; TRANS ETHNIC; TRANSETHNIC; WHITE COLONIALISM; WHITE
COLONIZATION; WHITE COLONIZER; WHITE COLONIZERS; WHITE FRAGILITY; WHITE HISTORICALLY; WHITE
NATIONALISM; WHITE NATIONALIST; WHITE PEOPLE; WHITE PERSON; WHITE PRIVILEGE; WHITE SERVING; WHITE
SUPREMACY; WHITENESS.
'''

environmentaljusticebanstring='''
CLIMATE ACTION; CLIMATE CONSCIOUS; CLIMATE CONSCIOUSNESS; CLIMATE EQUALITY; CLIMATE EQUITY;
CLIMATE JUSTICE; CLIMATE RESEARCH; ECO CULTURAL; ECOCULTURAL; ENVIRONMENT CONSCIOUS;
ENVIRONMENT CONSCIOUSNESS; ENVIRONMENTAL CONSCIOUS; ENVIRONMENTAL CONSCIOUSNESS;
ENVIRONMENTAL EQUALITY; ENVIRONMENTAL EQUITY; ENVIRONMENTAL GOVERNANCE; ENVIRONMENTAL JUSTICE;
ENVIRONMENTAL SOCIAL; ENVIRONMENTALGOVERNANCE; ENVIRONMENTALLY CONSCIOUS;
ENVIRONMENTALSOCIAL; ESG; ESG EFFORT; ESG EFFORTS; ESG INITIATIVE; ESG INITIATIVES; GREEN NEW
DEAL; NET ZERO; NETZERO; SOCIAL ENVIRONMENTAL; SOCIALENVIRONMENTAL; CLIMATE INJUSTICE; CLIMATE
JUSTICES; CLIMATE INJUSTICES; CLIMATE CHANGE; GREEN INFRASTRUCTURE; GREEN SOCIETY; CLEAN ENERGY.
'''

In [8]:
all_bans = [statusbanstring, socialbanstring, genderbanstring, racebanstring, environmentaljusticebanstring]


all_terms = []

for terms_str in all_bans:
    lis = terms_str.replace('\n','').replace('.','').split(';')
    lis = [i.lower().strip() for i in lis]
    
    all_terms += lis

senate_terms = set(all_terms)

len(senate_terms)

695

Senate terms cover more words, but the scope of the other flagged terms is likely different.

In [9]:
senate_terms

{'activism',
 'activist',
 'activists',
 'advance diversity',
 'advance inclusivity',
 'advance the diversity',
 'advancing diversity',
 'advancing inclusive',
 'advocacy',
 'advocate',
 'advocates',
 'affirmative action',
 'alliance for diversity',
 'ally',
 'allyship',
 'anti black',
 'anti black racism',
 'anti racism',
 'anti racist',
 'anti white',
 'antiblack',
 'antiblack racism',
 'antiracism',
 'antiracist',
 'antiwhite',
 'background inclusivity',
 'barrier',
 'barriers',
 'bi cultural',
 'bias toward',
 'bias towards',
 'biased',
 'biased toward',
 'biased towards',
 'biases',
 'biases toward',
 'biases towards',
 'bicultural',
 'bigot',
 'bigotry',
 'bipoc',
 'bipocx',
 'black and latinx',
 'black communities',
 'black cultural',
 'black culture',
 'black cultures',
 'black female',
 'black females',
 'black indigenous and latinx',
 'black indigenous and other',
 'black indigenous latinx',
 'black indigenous other',
 'black individual',
 'black individuals',
 'black intellectualism',
 'black livesmatter',
 'black male',
 'black males',
 'black men',
 'black minorities',
 'black minority',
 'black people',
 'black person',
 'black thought',
 'black women',
 'blackcommunity',
 'blackness',
 'blackvoices',
 'broaden diversity',
 'broaden the diversity',
 'cisgender',
 'cisnormative',
 'cisnormativity',
 'clean energy',
 'climate action',
 'climate change',
 'climate conscious',
 'climate consciousness',
 'climate equality',
 'climate equity',
 'climate injustice',
 'climate injustices',
 'climate justice',
 'climate research',
 'climatejustices',
 'colored communities',
 'colored community',
 'colored female',
 'colored females',
 'colored individual',
 'colored male',
 'colored males',
 'colored men',
 'colored minorities',
 'colored minority',
 'colored people',
 'colored person',
 'colored women',
 'coloredindividuals',
 'coloredvoices',
 'commitment to diversity',
 'community diversity',
 'community equity',
 'community inclusivity',
 'critical race theory',
 'cultural activism',
 'cultural activists',
 'cultural advocacy',
 'cultural advocate',
 'cultural and ethnic',
 'cultural and racial',
 'cultural appropriation',
 'cultural appropriations',
 'cultural bias',
 'cultural connections',
 'cultural differences',
 'cultural heritage',
 'cultural humility',
 'cultural inequalities',
 'cultural inequality',
 'cultural inequities',
 'cultural inequity',
 'cultural injustices',
 'cultural justice',
 'cultural relevance',
 'cultural segregation',
 'culturalactivist',
 'culturalcompetency',
 'culturalinjustice',
 'culturally attuned',
 'culturally biased',
 'culturally relevant',
 'culturally responsive',
 'culturally sensitive',
 'culturally sustaining',
 'culturallysustainable',
 'culture and ethnicity',
 'culture and race',
 'cultures and races',
 'cultures andethnicities',
 'de colonize',
 'de colonized',
 'de colonizing',
 'de segregate',
 'de segregated',
 'de segregation',
 'decolonization',
 'decolonize',
 'decolonized',
 'decolonizing',
 'dei',
 'deij',
 'desegregate',
 'desegregated',
 'desegregates',
 'desegregation',
 'disabilities',
 'disability',
 'discriminate',
 'discriminated',
 'discrimination',
 'discriminatory',
 'diverse background',
 'diverse backgrounds',
 'diverse community',
 'diverse group',
 'diverse groups',
 'diverse individual',
 'diverse status',
 'diverse statuses',
 'diverse voices',
 'diversecommunities',
 'diverseindividuals',
 'diversified',
 'diversify',
 'diversifying',
 'diversity and equity',
 'diversity and inclusion',
 'diversity and inclusivity',
 'diversity awareness',
 'diversity equity',
 'divisiveness',
 'eco cultural',
 'ecocultural',
 'emphasis on diversity',
 'emphasize diversity',
 'emphasizing diversity',
 'encouragediversity',
 'encouraging diversity',
 'enhance diversity',
 'enhance the diversity',
 'enhancing diversity',
 'environment conscious',
 'environment consciousness',
 'environmental conscious',
 'environmental consciousness',
 'environmental equality',
 'environmental equity',
 'environmental governance',
 'environmental justice',
 'environmental social',
 'environmentalgovernance',
 'environmentally conscious',
 'environmentalsocial',
 'equal opportunities',
 'equal opportunity',
 'equalities',
 'equality',
 'equitable',
 'equitable and inclusive',
 'equities',
 'equity',
 'esg',
 'esg effort',
 'esg efforts',
 'esg initiative',
 'esg initiatives',
 'ethnic and cultural',
 'ethnic and racial',
 'ethnic bias',
 'ethnic communities',
 'ethnic cultural',
 'ethnic culture',
 'ethnic cultures',
 'ethnic equity',
 'ethnic identities',
 'ethnic identity',
 'ethnic individual',
 'ethnic individuals',
 'ethnic minority',
 'ethnic people',
 'ethnic person',
 'ethnic racism',
 'ethnic segregation',
 'ethnic voices',
 'ethnical racism',
 'ethniccommunity',
 'ethnicdiversity',
 'ethnicities and cultures',
 'ethnicities and races',
 'ethnicity',
 'ethnicity and culture',
 'ethnicity and race',
 'ethnicminorities',
 'excluded',
 'exclusion',
 'exclusive',
 'feel seen and heard',
 'female',
 'female voices',
 'females',
 'femininity',
 'feminism',
 'feminist',
 'feministic',
 'fluid identity',
 'foster diversity',
 'fostering diversity',
 'fostering inclusive',
 'fostering inclusivity',
 'fostering the diversity',
 'gender',
 'gender acceptance',
 'gender affirmation',
 'gender affirming',
 'gender and sexual',
 'gender appreciation',
 'gender based',
 'gender binary',
 'gender disparities',
 'gender disparity',
 'gender diversity',
 'gender dysmorphia',
 'gender fluid',
 'gender fluidity',
 'gender identity',
 'gender ideology',
 'gender inclusive',
 'gender inclusivity',
 'gender marginalized',
 'gender minorities',
 'gender minority',
 'gender neural',
 'gender non binary',
 'gender non conforming',
 'gender nonbinary',
 'gender nonconforming',
 'gender oppression',
 'gender preference',
 'gender preferences',
 'gender spectrum',
 'gender transition',
 'gender transitioning',
 'gender typical',
 'genderdiscrimination',
 'genderdysphoria',
 'genders',
 'genderstereotypes',
 'green infrastructure',
 'green newdeal',
 'green society',
 'group inclusivity',
 'groupequity',
 'hate speech',
 'heterosexual',
 'hispanic community',
 'hispanic cultural',
 'hispanic culture',
 'hispanic cultures',
 'hispanic female',
 'hispanic females',
 'hispanic individual',
 'hispanic individuals',
 'hispanic male',
 'hispanic males',
 'hispanic men',
 'hispanic minorities',
 'hispanic minority',
 'hispanic people',
 'hispanic person',
 'hispanic voices',
 'hispanic women',
 'hispaniccommunities',
 'historical racism',
 'historically',
 'historically male',
 'historically racist',
 'historically white',
 'implicit bias',
 'implicit biases',
 'inclusion',
 'inclusive',
 'inclusive language',
 'inclusiveness',
 'inclusivity',
 'inclusivity and diversity',
 'increase diversity',
 'increase the diversity',
 'increases diversity',
 'increases the diversity',
 'increasing diversity',
 'increasingthe diversity',
 'indigenous communities',
 'indigenous community',
 'indigenous cultural',
 'indigenous culture',
 'indigenous cultures',
 'indigenous female',
 'indigenous females',
 'indigenous individual',
 'indigenous individuals',
 'indigenous male',
 'indigenous males',
 'indigenous men',
 'indigenous minorities',
 'indigenous minority',
 'indigenous people',
 'indigenous person',
 'indigenous voices',
 'indigenous women',
 'inequalities',
 'inequality',
 'inequitable',
 'inequities',
 'inequity',
 'injustice',
 'injustices',
 'institutional',
 'institutional racism',
 'institutionalize',
 'institutionalized',
 'institutionalizedracism',
 'institutionally',
 'institutionally racist',
 'inter cultural',
 'inter culturally',
 'inter racial',
 'inter racially',
 'intercultural',
 'interculturally',
 'intergenerational trauma',
 'interracial',
 'interracially',
 'intersectional',
 'intersectional feminism',
 'intersectionality',
 'lack of diversity',
 'latina community',
 'latina female',
 'latina females',
 'latina individual',
 'latina individuals',
 'latina males',
 'latina men',
 'latina minorities',
 'latina people',
 'latina person',
 'latina voices',
 'latina women',
 'latinacommunities',
 'latinamale',
 'latinaminority',
 'latinx communities',
 'latinx community',
 'latinx cultural',
 'latinx culture',
 'latinx cultures',
 'latinx female',
 'latinx females',
 'latinx individual',
 'latinx individuals',
 'latinx male',
 'latinx men',
 'latinx minorities',
 'latinx minority',
 'latinx people',
 'latinx voices',
 'latinx women',
 'latinxmales',
 'latinxperson',
 'lgbt',
 'lgbtq',
 'lgbtq+',
 'lgbtqia',
 'male dominant',
 'maledominated',
 'marginalization',
 'marginalize',
 'marginalized',
 'masculine',
 'masculinity',
 'micro aggression',
 'micro aggressive',
 'micro aggressiveness',
 'microaggression',
 'microaggressions',
 'microaggressive',
 'microaggressiveness',
 'minorities',
 'minority',
 'mis gender',
 'misgender',
 'misogynistic',
 'misogyny',
 'multi cultural',
 'multi culturally',
 'multi ethnic',
 'multi ethnically',
 'multicultural',
 'multiculturally',
 'multiethnic',
 'multiethnically',
 'net zero',
 'netzero',
 'non binary',
 'non binary gender',
 'non black',
 'non conforming gender',
 'non white',
 'nonbinary',
 'nonbinary gender',
 'nonblack',
 'nonconforminggender',
 'nonwhite',
 'oppressed',
 'oppressed gender',
 'oppressed genders',
 'oppressed sexualities',
 'oppression',
 'oppressive',
 'oppressiveness',
 'pansexual',
 'people of color',
 'poc',
 'pocx',
 'polarization',
 'polarize',
 'political',
 'politicization',
 'politicize',
 'predominately white',
 'predominatelymale',
 'preferred gender',
 'preferred identity',
 'preferred sex',
 'prejudice',
 'prejudices',
 'primarily male',
 'primarilywhite',
 'privilege',
 'privileged',
 'privileged white',
 'privileges',
 'pro black',
 'pro white',
 'problack',
 'promote diversity',
 'promoting diversity',
 'pronoun',
 'pronouns',
 'prowhite',
 'queer theory',
 'race and culture',
 'race andethnicity',
 'race based',
 'racebased',
 'races and cultures',
 'races and ethnicities',
 'racial',
 'racial and ethnic',
 'racial andcultural',
 'racial bias',
 'racial biases',
 'racial disparities',
 'racial disparity',
 'racial identity',
 'racial inequalities',
 'racial inequality',
 'racial inequities',
 'racial inequity',
 'racial injustice',
 'racial injustices',
 'racial justice',
 'racial minorities',
 'racial minority',
 'racial prejudice',
 'racial prejudices',
 'racial segregation',
 'racial socialization',
 'racial stereotypes',
 'racial violence',
 'racialdiversity',
 'racially',
 'racially and culturally',
 'racially bias',
 'racially biased',
 'racially oppressed',
 'racialoppression',
 'racialsolidarity',
 'racism',
 'racist',
 'reparation',
 'reparations',
 'safe space',
 'safe spaces',
 'segregated',
 'segregated cultures',
 'segregated ethnicities',
 'segregated ethnicity',
 'segregated race',
 'segregated races',
 'segregation',
 'self identify',
 'sense of belongingness',
 'sense ofbelonging',
 'sex change',
 'sex preference',
 'sex transition',
 'sexism',
 'sexist',
 'sexual disparities',
 'sexual disparity',
 'sexual identity',
 'sexual minorities',
 'sexual preference',
 'sexual preferences',
 'sexualdiscrimination',
 'sexualities',
 'sexuality',
 'sexualminority',
 'social activism',
 'social activist',
 'social activists',
 'social advocacy',
 'social bias',
 'social biases',
 'social environmental',
 'social inequalities',
 'social inequality',
 'social inequities',
 'social inequity',
 'social injustice',
 'social injustices',
 'social justice',
 'social justice activism',
 'social justice advocate',
 'socialadvocate',
 'socialenvironmental',
 'socialjustice advocacy',
 'socially biased',
 'socially relevant',
 'socio cultural',
 'socio culturally',
 'socio economic',
 'sociocultural',
 'socioculturally',
 'socioeconomic',
 'status',
 'statuses',
 'stereotype',
 'stereotypes',
 'stereotypical',
 'stereotyping',
 'straight white',
 'structural inequality',
 'structural inequity',
 'structural racism',
 'structurally racist',
 'support diversity',
 'supporting diversity',
 'system of oppression',
 'systematic oppression',
 'systematically oppressed',
 'systemic',
 'systemic oppression',
 'systemic racism',
 'systemical',
 'systemically',
 'systemically oppressed',
 'systemically racist',
 'systems of oppression',
 'systems of power',
 'tokenistic',
 'tokensim',
 'toxicmasculinity',
 'trans cultural',
 'trans ethnic',
 'transcultural',
 'transethnic',
 'transgender',
 'transgenderism',
 'transitioning gender',
 'transitioning sex',
 'transjustice',
 'transphobia',
 'transphobic',
 'trauma',
 'traumatic',
 'under appreciated',
 'under appreciation',
 'under privilege',
 'under privileged',
 'under representation',
 'under represented',
 'under served',
 'under serving',
 'under valuing',
 'underappreciated',
 'underappreciation',
 'underprivilege',
 'underprivileged',
 'underrepresentation',
 'underrepresented',
 'underrepresented gender',
 'underserved',
 'underserving',
 'undervalued',
 'undervaluing',
 'unequal opportunities',
 'unequal opportunity',
 'unjust',
 'victim',
 'victimhood',
 'victimized',
 'victims',
 'voices are acknowledged',
 'voices heard',
 'voices of women',
 'voicesmatter',
 'welcoming environment',
 'white colonialism',
 'white colonizer',
 'white colonizers',
 'white female',
 'white fragility',
 'white historically',
 'white male',
 'white males',
 'white men',
 'white nationalist',
 'white people',
 'white person',
 'white privilege',
 'white serving',
 'white women',
 'whitecolonization',
 'whitefemales',
 'whitenationalism',
 'whiteness',
 'whitesupremacy',
 'women',
 'women and gender',
 'women and underrepresented',
 'womenunderrepresented'}

In [10]:
flagged_new

{'accessible',
 'activism',
 'activists',
 'advocacy',
 'advocate',
 'advocates',
 'affirming care',
 'allyship',
 'anti-racism',
 'antiracist',
 'assigned at birth',
 'assigned female at birth',
 'assigned male at birth',
 'at risk',
 'barrier',
 'barriers',
 'belong',
 'bias',
 'biased',
 'biased toward',
 'biases',
 'biases towards',
 'bipoc',
 'black',
 'climate science',
 'community diversity',
 'cultural competence',
 'cultural differences',
 'cultural sensitivity',
 'culturally appropriate',
 'culturally responsive',
 'dei',
 'deia',
 'disabilities',
 'disability',
 'discriminated',
 'discrimination',
 'discriminatory',
 'disparity',
 'diverse',
 'diverse backgrounds',
 'diverse communities',
 'diverse community',
 'diverse group',
 'diverse groups',
 'diversified',
 'diversify',
 'diversifying',
 'diversity',
 'enhance the diversity',
 'enhancing diversity',
 'equality',
 'equitable',
 'equity',
 'ethnicity',
 'excluded',
 'exclusion',
 'expression',
 'female',
 'females',
 'gender',
 'gender based',
 'gender diversity',
 'gender identity',
 'gender-affirming care',
 'genders',
 'hate speech',
 'health disparity',
 'health equity',
 'hesitancy',
 'hesitant',
 'historically',
 'identity',
 'immigrants',
 'implicit bias',
 'implicit biases',
 'inclusion',
 'inclusive',
 'inclusiveness',
 'inclusivity',
 'increase diversity',
 'increase the diversity',
 'indigenous community',
 'inequalities',
 'inequality',
 'inequitable',
 'inequities',
 'inequity',
 'injustice',
 'institutional',
 'intersectional',
 'intersectionality',
 'key groups',
 'key populations',
 'latinx',
 'lgbt',
 'lgbtq',
 'marginalize',
 'marginalized',
 'men who have sex with men',
 'mental health',
 'minorities',
 'minority',
 'most risk',
 'mrna',
 'msm',
 'multicultural',
 'mx',
 'native american',
 'non-binary',
 'nonbinary',
 'oppression',
 'oppressive',
 'orientation',
 'person-centered',
 'person-centered care',
 'polarization',
 'political',
 'pollution',
 'pregnant people',
 'pregnant person',
 'pregnant persons',
 'prejudice',
 'privilege',
 'promote diversity',
 'promoting diversity',
 'pronoun',
 'race',
 'race and ethnicity',
 'racial',
 'racial diversity',
 'racial identity',
 'racial inequality',
 'racial justice',
 'racially',
 'racism',
 'segregation',
 'sense of belonging',
 'sex',
 'sexuality',
 'social justice',
 'sociocultural',
 'socioeconomic',
 'status',
 'stereotype',
 'stereotypes',
 'systemic',
 'systemically',
 'trans',
 'transgender',
 'trauma',
 'traumatic',
 'tribal',
 'underappreciated',
 'underprivileged',
 'underrepresentation',
 'underrepresented',
 'underserved',
 'vaccinate',
 'vaccination',
 'vaccine',
 'vaccines',
 'victim',
 'victims',
 'vulnerable populations',
 'women',
 'women and underrepresented'}

In [11]:
diff = list(senate_terms - flagged_new)
diff

['racial minorities',
 'broaden the diversity',
 'diverse statuses',
 'unequal opportunities',
 'social environmental',
 'ethnic identities',
 'ethnic identity',
 'ethnic racism',
 'environmental social',
 'injustices',
 'transgenderism',
 'clean energy',
 'anti black',
 'bigotry',
 'antiblack',
 'hispanic people',
 'historically male',
 'increases the diversity',
 'intersectional feminism',
 'diverse individual',
 'socio economic',
 'racial inequalities',
 'micro aggressive',
 'white historically',
 'gender non binary',
 'culturalactivist',
 'fostering the diversity',
 'cisgender',
 'segregated',
 'multi cultural',
 'latina female',
 'gender and sexual',
 'gender nonconforming',
 'latinx minority',
 'cultural connections',
 'hispanic men',
 'latinx individual',
 'blackcommunity',
 'reparations',
 'ethnic individual',
 'safe spaces',
 'racial injustice',
 'social inequalities',
 'straight white',
 'microaggressions',
 'cultural activists',
 'female voices',
 'black person',
 'equal opportunities',
 'racial violence',
 'indigenous person',
 'black female',
 'cultural and racial',
 'netzero',
 'gender fluid',
 'lgbtq+',
 'emphasizing diversity',
 'segregated races',
 'trans ethnic',
 'community equity',
 'historically white',
 'race andethnicity',
 'latinxmales',
 'indigenous cultures',
 'voicesmatter',
 'black minority',
 'welcoming environment',
 'de colonize',
 'hispanic culture',
 'social justice advocate',
 'white men',
 'ethnic individuals',
 'segregated ethnicity',
 'intergenerational trauma',
 'black females',
 'black individuals',
 'social inequality',
 'under represented',
 'racial socialization',
 'social justice activism',
 'black cultures',
 'racial and ethnic',
 'cultural heritage',
 'racially and culturally',
 'white colonizer',
 'cultural bias',
 'latinx communities',
 'socialadvocate',
 'toxicmasculinity',
 'stereotypical',
 'lack of diversity',
 'emphasize diversity',
 'cultural inequalities',
 'mis gender',
 'culture and race',
 'inclusive language',
 'problack',
 'diverse background',
 'sense ofbelonging',
 'culturallysustainable',
 'latina women',
 'feminism',
 'latinx women',
 'desegregates',
 'socialenvironmental',
 'masculinity',
 'black indigenous other',
 'inter racial',
 'green infrastructure',
 'indigenous female',
 'cultural inequities',
 'bipocx',
 'white males',
 'encouragediversity',
 'culturally sensitive',
 'black indigenous and latinx',
 'historically racist',
 'multi ethnically',
 'latinx men',
 'decolonization',
 'preferred identity',
 'latinx females',
 'black livesmatter',
 'oppressed',
 'inclusivity and diversity',
 'white male',
 'stereotyping',
 'gender disparity',
 'indigenous men',
 'indigenous individuals',
 'esg initiatives',
 'black culture',
 'ethnic culture',
 'white nationalist',
 'indigenous women',
 'systematic oppression',
 'latinx voices',
 'lgbtqia',
 'bigot',
 'culturalinjustice',
 'blackvoices',
 'transitioning sex',
 'black communities',
 'desegregation',
 'racial prejudice',
 'hispanic person',
 'de segregation',
 'latinacommunities',
 'cultural inequity',
 'transjustice',
 'gender binary',
 'whitecolonization',
 'multi culturally',
 'sexism',
 'racially bias',
 'gender neural',
 'cultural activism',
 'ethnic communities',
 'racial andcultural',
 'racial stereotypes',
 'gender dysmorphia',
 'ethnic person',
 'prejudices',
 'hispanic cultures',
 'non white',
 'diversity awareness',
 'pro white',
 'gender ideology',
 'multiethnically',
 'segregated ethnicities',
 'sexual disparity',
 'colored people',
 'race based',
 'whitenationalism',
 'misogyny',
 'bias towards',
 'hispanic female',
 'de segregated',
 'transphobia',
 'environmental consciousness',
 'multiculturally',
 'latina minorities',
 'hispaniccommunities',
 'latina individual',
 'cisnormative',
 'climate justice',
 'diverse status',
 'gender minorities',
 'sexual minorities',
 'indigenous minorities',
 'cultural appropriations',
 'social activist',
 'segregated cultures',
 'racial inequities',
 'white serving',
 'sexualminority',
 'decolonize',
 'encouraging diversity',
 'cultural injustices',
 'ethnic segregation',
 'cultural appropriation',
 'white person',
 'interracially',
 'feel seen and heard',
 'racebased',
 'hispanic male',
 'undervaluing',
 'voices heard',
 'latina individuals',
 'latina people',
 'microaggressive',
 'climate injustices',
 'black males',
 'inter cultural',
 'black women',
 'latinamale',
 'male dominant',
 'environmentalgovernance',
 'pocx',
 'systems of oppression',
 'black people',
 'equal opportunity',
 'under privileged',
 'whiteness',
 'sex preference',
 'undervalued',
 'ethnic minority',
 'divisiveness',
 'pro black',
 'poc',
 'safe space',
 'indigenous culture',
 'white women',
 'antiracism',
 'colored women',
 'black indigenous latinx',
 'black thought',
 'gender inclusivity',
 'femininity',
 'climate consciousness',
 'preferred gender',
 'under serving',
 'people of color',
 'segregated race',
 'white fragility',
 'net zero',
 'cultures and races',
 'gender oppression',
 'equalities',
 'hispanic minority',
 'cultural humility',
 'latinaminority',
 'critical race theory',
 'non black',
 'racially biased',
 'de colonizing',
 'nonconforminggender',
 'transethnic',
 'hispanic individual',
 'ethnic equity',
 'climate injustice',
 'activist',
 'exclusive',
 'genderstereotypes',
 'enhance diversity',
 'biases toward',
 'interculturally',
 'environment conscious',
 'cultural justice',
 'desegregated',
 'racial minority',
 'alliance for diversity',
 'colored female',
 'gender minority',
 'black and latinx',
 'racialdiversity',
 'ethnic bias',
 'increases diversity',
 'colored minorities',
 'hispanic cultural',
 'deij',
 'latinx people',
 'white people',
 'ethniccommunity',
 'transitioning gender',
 'environmental equality',
 'culture and ethnicity',
 'unjust',
 'socialjustice advocacy',
 'racialoppression',
 'tokenistic',
 'intercultural',
 'gender transition',
 'racial biases',
 'micro aggression',
 'social activism',
 'trans cultural',
 'eco cultural',
 'structural inequity',
 'systemically racist',
 'historical racism',
 'cultural segregation',
 'racial inequity',
 'indigenous individual',
 'oppressiveness',
 'system of oppression',
 'privileged white',
 'sexualities',
 'gender appreciation',
 'gender disparities',
 'heterosexual',
 'latinx minorities',
 'social injustice',
 'racial bias',
 'culturally attuned',
 'multi ethnic',
 'tokensim',
 'ethnicity and culture',
 'colored person',
 'environmental justice',
 'gender preferences',
 'inter culturally',
 'social inequities',
 'climate research',
 'gender inclusive',
 'polarize',
 'nonbinary gender',
 'structural inequality',
 'ecocultural',
 'latinxperson',
 'indigenous males',
 'ethnicities and races',
 'groupequity',
 'ethnic voices',
 'ethnic and cultural',
 'climate conscious',
 'whitefemales',
 'cisnormativity',
 'fluid identity',
 'culturalcompetency',
 'esg initiative',
 'sense of belongingness',
 'socioculturally',
 'ethnic cultural',
 'de segregate',
 'sex transition',
 'sexual identity',
 'women and gender',
 'systemic racism',
 'colored men',
 'pansexual',
 'latinx community',
 'colored communities',
 'feministic',
 'esg',
 'bicultural',
 'oppressed gender',
 'antiwhite',
 'social inequity',
 'diversecommunities',
 'indigenous minority',
 'structurally racist',
 'colored individual',
 'ally',
 'underserving',
 'racially oppressed',
 'socio culturally',
 'ethnicminorities',
 'white female',
 'socially relevant',
 'green newdeal',
 'discriminate',
 'nonblack',
 'hispanic community',
 'equities',
 'prowhite',
 'gender preference',
 'climate change',
 'racist',
 'under appreciation',
 'politicization',
 'politicize',
 'anti racist',
 'blackness',
 'environment consciousness',
 'latinx culture',
 'affirmative action',
 'bi cultural',
 'environmental governance',
 'advancing inclusive',
 'gender transitioning',
 'fostering inclusive',
 'victimhood',
 'institutionalize',
 'interracial',
 'hispanic individuals',
 'latina community',
 'socio cultural',
 'white colonizers',
 'structural racism',
 'oppressed sexualities',
 'indigenous cultural',
 'under appreciated',
 'institutionally',
 'institutional racism',
 'social biases',
 'social activists',
 'gender marginalized',
 'advance the diversity',
 'underprivilege',
 'social advocacy',
 'gender affirmation',
 'coloredindividuals',
 'biased towards',
 'gender acceptance',
 'green society',
 'systems of power',
 'anti racism',
 'institutionally racist',
 'gender non conforming',
 'colored male',
 'genderdysphoria',
 'underrepresented gender',
 'latina voices',
 'diversity and equity',
 'womenunderrepresented',
 'systemic oppression',
 'increasing diversity',
 'whitesupremacy',
 'black intellectualism',
 'ethnic cultures',
 'hispanic women',
 'colored community',
 'ethnicity and race',
 'sexualdiscrimination',
 'ethnical racism',
 'unequal opportunity',
 'gender fluidity',
 'non binary',
 'anti white',
 'nonwhite',
 'latinx cultural',
 'non binary gender',
 'coloredvoices',
 'supporting diversity',
 'pronouns',
 'micro aggressiveness',
 'social bias',
 'primarilywhite',
 'underappreciation',
 'commitment to diversity',
 'culturally relevant',
 'indigenous communities',
 'cultures andethnicities',
 'ethnic people',
 'preferred sex',
 'systemical',
 'black indigenous and other',
 'latina person',
 'misogynistic',
 'maledominated',
 'background inclusivity',
 'bias toward',
 'under representation',
 'sexual preference',
 'fostering inclusivity',
 'predominatelymale',
 'colored males',
 'sexual disparities',
 'racial disparities',
 'under served',
 'oppressed genders',
 'ethnic and racial',
 'broaden diversity',
 'systematically oppressed',
 'hispanic minorities',
 'black cultural',
 'voices are acknowledged',
 'cultural inequality',
 'transphobic',
 'reparation',
 'environmental conscious',
 'indigenous females',
 'gender spectrum',
 'environmentally conscious',
 'diversity equity',
 'predominately white',
 'indigenous people',
 'hispanic voices',
 'climatejustices',
 'indigenous male',
 'antiblack racism',
 'culturally biased',
 'climate action',
 'emphasis on diversity',
 'transcultural',
 'masculine',
 'desegregate',
 'foster diversity',
 'race and culture',
 'advance diversity',
 'racial disparity',
 'racial injustices',
 'hispanic males',
 'de colonized',
 'black individual',
 'statuses',
 'privileged',
 'latinx individuals',
 'gender affirming',
 'sex change',
 'racial segregation',
 'inter racially',
 'racialsolidarity',
 'queer theory',
 'multiethnic',
 'community inclusivity',
 'latinx female',
 'victimized',
 'gender typical',
 'increasingthe diversity',
 'colored females',
 'marginalization',
 'cultural advocacy',
 'privileges',
 'ethnicdiversity',
 'anti black racism',
 'black men',
 'cultural advocate',
 'systemically oppressed',
 'decolonizing',
 'esg efforts',
 'voices of women',
 'black male',
 'latina males',
 'environmentalsocial',
 'microaggressiveness',
 'self identify',
 'institutionalized',
 'latinx male',
 'under privilege',
 'black minorities',
 'latina men',
 'primarily male',
 'diversity and inclusion',
 'white privilege',
 'racial prejudices',
 'gender nonbinary',
 'decolonized',
 'latinx cultures',
 'ethnicities and cultures',
 'microaggression',
 'races and cultures',
 'institutionalizedracism',
 'hispanic females',
 'diverseindividuals',
 'sexist',
 'socially biased',
 'indigenous voices',
 'climate equity',
 'diversity and inclusivity',
 'latina females',
 'races and ethnicities',
 'cultural and ethnic',
 'feminist',
 'white colonialism',
 'sexual preferences',
 'equitable and inclusive',
 'esg effort',
 'advance inclusivity',
 'colored minority',
 'support diversity',
 'cultural relevance',
 'climate equality',
 'diverse voices',
 'misgender',
 'genderdiscrimination',
 'group inclusivity',
 'social injustices',
 'non conforming gender',
 'fostering diversity',
 'under valuing',
 'environmental equity',
 'advancing diversity',
 'culturally sustaining']

In [12]:
list(flagged_new - senate_terms)

['hesitant',
 'assigned at birth',
 'black',
 'vaccinate',
 'gender-affirming care',
 'expression',
 'mx',
 'sex',
 'pollution',
 'culturally appropriate',
 'at risk',
 'msm',
 'racial diversity',
 'vaccine',
 'assigned male at birth',
 'key populations',
 'deia',
 'bias',
 'tribal',
 'person-centered care',
 'pregnant person',
 'health disparity',
 'disparity',
 'vaccines',
 'affirming care',
 'person-centered',
 'health equity',
 'anti-racism',
 'vulnerable populations',
 'climate science',
 'orientation',
 'men who have sex with men',
 'race and ethnicity',
 'mental health',
 'diverse communities',
 'latinx',
 'sense of belonging',
 'key groups',
 'most risk',
 'trans',
 'native american',
 'immigrants',
 'non-binary',
 'diverse',
 'mrna',
 'pregnant people',
 'accessible',
 'diversity',
 'identity',
 'race',
 'vaccination',
 'cultural competence',
 'pregnant persons',
 'belong',
 'hesitancy',
 'cultural sensitivity',
 'assigned female at birth']

https://www.science.org/doi/abs/10.1126/science.1136800
Affinity propagation for clustering words in list

find which senate-specified words are in abstracts

In [13]:
flagged = []

for i in df['abstract'].str.lower():
    curr = []
    if i != i:  #add nans
        continue
    for j in senate_terms:
        if j in i:
            curr.append(j)
    flagged.append(curr)

In [14]:
flagged

[[],
 ['ally'],
 ['biased'],
 ['ally'],
 ['ally'],
 ['ally'],
 ['barrier', 'ally'],
 ['poc', 'ally'],
 ['minority', 'victim', 'heterosexual', 'ally', 'discrimination', 'victims'],
 ['historically',
  'gender',
  'minority',
  'victim',
  'heterosexual',
  'ally',
  'women',
  'victims'],
 ['exclusive', 'ally', 'women'],
 ['ally'],
 ['women'],
 ['minority', 'female', 'heterosexual', 'ally', 'women'],
 ['women'],
 ['gender identity',
  'lgbtq+',
  'gender',
  'sexism',
  'minority',
  'victim',
  'female',
  'lgbtq',
  'heterosexual',
  'lgbt',
  'racial',
  'ally',
  'sexist'],
 ['ally'],
 ['ally'],
 [],
 ['marginalize',
  'minority',
  'sexual minorities',
  'intersectional',
  'status',
  'ethnicity',
  'minorities',
  'heterosexual',
  'sexual identity',
  'ally',
  'equitable',
  'marginalized',
  'marginalization'],
 [],
 ['gender identity',
  'gender',
  'minority',
  'equity',
  'intersectional',
  'activist',
  'gender minority',
  'advocate',
  'ethnicity',
  'ally',
  'intersectionality',
  'activists'],
 ['ally', 'women'],
 ['ally'],
 ['gender', 'ally'],
 [],
 ['sociocultural',
  'latina women',
  'gender',
  'racially',
  'minority',
  'intersectional',
  'black women',
  'underrepresentation',
  'sexuality',
  'heterosexual',
  'socioeconomic',
  'racial',
  'ally',
  'women'],
 ['ally', 'trauma'],
 ['ally'],
 ['excluded', 'ally'],
 ['racial and ethnic',
  'diverse background',
  'gender',
  'underserved',
  'diverse backgrounds',
  'racial',
  'ally',
  'diverse group',
  'underrepresented'],
 ['gender',
  'minority',
  'gender minority',
  'ethnicity',
  'heterosexual',
  'sexual identity',
  'women'],
 ['marginalize',
  'culturally sensitive',
  'sexism',
  'minority',
  'intersectional',
  'ethnic minority',
  'ethnicity',
  'oppression',
  'racism',
  'heterosexual',
  'racial',
  'ally',
  'racist',
  'institutional',
  'marginalized',
  'discrimination'],
 ['inequities', 'equities'],
 ['lgbtq+',
  'minority',
  'victim',
  'lgbtq',
  'heterosexual',
  'lgbt',
  'ally',
  'women'],
 ['cisgender',
  'gender identity',
  'gender',
  'minority',
  'gender minority',
  'ethnicity',
  'inequities',
  'heterosexual',
  'ally',
  'equities',
  'culturally relevant'],
 ['inclusive', 'ally', 'institutional'],
 ['gender identity',
  'gender',
  'minority',
  'sexual minorities',
  'gender minority',
  'ethnicity',
  'minorities',
  'heterosexual',
  'sexual identity',
  'ally',
  'discrimination'],
 ['gender identity',
  'gender',
  'minority',
  'sexual minorities',
  'gender minority',
  'ethnicity',
  'minorities',
  'heterosexual',
  'sexual identity',
  'ally',
  'discrimination'],
 ['cisgender',
  'microaggressions',
  'gender',
  'systematic oppression',
  'racially',
  'minority',
  'intersectional',
  'status',
  'ethnicity',
  'oppression',
  'inequities',
  'racial',
  'ally',
  'intersectionality',
  'equities',
  'masculine',
  'discrimination',
  'transgender',
  'microaggression'],
 ['ally'],
 ['ally'],
 ['marginalize',
  'cisgender',
  'gender identity',
  'gender',
  'minority',
  'female',
  'exclusive',
  'sexuality',
  'sexual identity',
  'ally',
  'marginalized'],
 ['ally', 'women'],
 ['ally'],
 ['cisgender',
  'lgbtq+',
  'gender',
  'minority',
  'transphobia',
  'gender minorities',
  'lgbtq',
  'minorities',
  'heterosexual',
  'lgbt',
  'ally',
  'discrimination',
  'transgender'],
 ['ally'],
 ['ally'],
 ['lgbtq+',
  'gender',
  'minority',
  'transphobia',
  'lgbtq',
  'gender minority',
  'lgbt'],
 ['cisgender', 'gender', 'minority', 'equality', 'gender minority', 'ally'],
 ['lgbtq+',
  'gender',
  'minority',
  'victim',
  'lgbtq',
  'gender minority',
  'lgbt',
  'ally',
  'victims'],
 ['barrier',
  'barriers',
  'racially',
  'ethnicity',
  'socioeconomic',
  'racial',
  'ally'],
 ['ally'],
 ['reparation'],
 ['ally'],
 ['stereotypes', 'minority', 'heterosexual', 'ally', 'women', 'stereotype'],
 ['ally'],
 ['victim', 'female', 'females', 'ally'],
 ['barrier', 'barriers', 'ally'],
 [],
 ['gender',
  'female',
  'females',
  'ally',
  'women',
  'inclusion',
  'diversity and inclusion'],
 ['ally'],
 ['ally', 'women', 'trauma'],
 ['ally'],
 ['gender',
  'victim',
  'sexualities',
  'heterosexual',
  'ally',
  'women',
  'inclusion'],
 ['barrier', 'ally'],
 ['barrier',
  'cisgender',
  'barriers',
  'lgbtq+',
  'gender',
  'culturally sensitive',
  'transphobia',
  'lgbtq',
  'intersectional',
  'enhance diversity',
  'lgbt',
  'ally',
  'inclusion',
  'trauma',
  'transgender',
  'diversity and inclusion'],
 ['traumatic',
  'misogyny',
  'minority',
  'victim',
  'heterosexual',
  'ally',
  'women',
  'trauma',
  'sexist'],
 ['minority'],
 ['cisgender',
  'gender',
  'minority',
  'gender minority',
  'ally',
  'women',
  'discrimination'],
 ['women'],
 ['ally'],
 ['poc'],
 [],
 ['racially', 'minority', 'racial', 'ally'],
 ['historically', 'ally', 'underrepresented'],
 ['ally'],
 ['ally'],
 ['status', 'ethnicity', 'socioeconomic', 'ally', 'institutional'],
 [],
 ['poc', 'ally'],
 ['systemic', 'ally'],
 ['ally'],
 ['ally'],
 ['ally'],
 ['ally'],
 ['ally'],
 ['disabilities', 'socioeconomic', 'ally', 'women'],
 ['racial and ethnic',
  'minority',
  'ethnic minority',
  'disabilities',
  'diversify',
  'racial',
  'ally',
  'underrepresented',
  'advancing diversity'],
 ['ally', 'biased'],
 ['systemic', 'ally'],
 ['gender',
  'gender minorities',
  'minorities',
  'women',
  'gender affirming',
  'transgender'],
 ['status'],
 ['ally'],
 ['disabilities', 'minorities', 'ally', 'women'],
 ['status', 'ally'],
 ['minority',
  'diversify',
  'ally',
  'underrepresented',
  'institutional',
  'enhancing diversity',
  'advancing diversity'],
 ['status', 'ally'],
 ['barrier', 'ally'],
 ['poc', 'ally'],
 ['female', 'status', 'females', 'women'],
 ['historically',
  'minority',
  'ethnic minority',
  'ally',
  'institutional',
  'advancing diversity'],
 ['ally', 'institutional'],
 ['ally', 'privilege', 'privileged'],
 [],
 ['poc', 'ally'],
 ['racial and ethnic',
  'poc',
  'status',
  'black and latinx',
  'ethnicity',
  'socioeconomic',
  'racial',
  'ally'],
 ['gender', 'minority', 'ally', 'underrepresented'],
 ['racially', 'racial', 'ally'],
 [],
 ['ally', 'disability'],
 ['status', 'socioeconomic', 'ally'],
 ['ally', 'multiethnic'],
 ['sociocultural',
  'historically',
  'minority',
  'excluded',
  'equalities',
  'ally',
  'inequalities'],
 ['social environmental', 'ally', 'institutional'],
 ['ally'],
 ['sociocultural',
  'gender',
  'minority',
  'equity',
  'women and gender',
  'ally',
  'women',
  'underrepresented'],
 ['ally'],
 ['gender', 'sexual minorities', 'diversified', 'minorities', 'women'],
 [],
 [],
 ['ally'],
 ['ally'],
 ['ethnicity'],
 ['underserved', 'ally', 'biased'],
 ['poc', 'exclusion'],
 ['racial minorities',
  'racially',
  'minorities',
  'socioeconomic',
  'racial',
  'ally'],
 [],
 ['gender identity',
  'lgbtq+',
  'gender',
  'minority',
  'lgbtq',
  'inclusive',
  'gender minority',
  'lgbt',
  'ally',
  'underrepresented'],
 ['cisgender',
  'gender and sexual',
  'gender',
  'minority',
  'gender minorities',
  'equity',
  'lgbtq',
  'inclusive',
  'dei',
  'gender minority',
  'status',
  'minorities',
  'lgbt',
  'ally',
  'inclusion',
  'transgender',
  'diversity and inclusion'],
 ['ally', 'biased'],
 ['racial and ethnic',
  'lack of diversity',
  'gender',
  'female',
  'ethnicity',
  'minorities',
  'racial',
  'ally'],
 ['poc'],
 [],
 ['status', 'ally', 'inclusion'],
 ['biases', 'ally'],
 ['ally'],
 ['ally'],
 ['ethnicity', 'minorities', 'racial', 'ally'],
 ['ally'],
 ['ally'],
 ['status', 'ally'],
 ['racial', 'ally', 'ethnic and racial'],
 ['historically',
  'diverse background',
  'diverse backgrounds',
  'ally',
  'underrepresented',
  'advancing diversity'],
 ['socioeconomic', 'racial', 'ally', 'underrepresented'],
 ['diversified', 'ally'],
 [],
 ['systemic', 'ally'],
 ['biased'],
 ['ally'],
 ['ally'],
 ['sociocultural',
  'latinx communities',
  'status',
  'socioeconomic',
  'bicultural'],
 ['ally'],
 [],
 ['ally'],
 ['minority', 'ethnic minority', 'racial', 'ally'],
 ['ally', 'biased'],
 ['ally'],
 ['historically',
  'minority',
  'ally',
  'underrepresented',
  'advancing diversity'],
 ['traumatic', 'poc', 'ally', 'trauma'],
 ['ally'],
 ['institutional'],
 ['poc', 'ally'],
 ['barrier',
  'barriers',
  'equity',
  'poc',
  'status',
  'socioeconomic',
  'ally',
  'disability'],
 ['advocate', 'ally', 'advocates'],
 ['poc', 'ally'],
 ['ally'],
 [],
 ['ally'],
 ['systemic', 'ally', 'biased'],
 ['poc', 'ally'],
 ['status', 'socioeconomic', 'ally'],
 ['biased'],
 ['ally'],
 ['social environmental',
  'black women',
  'racial',
  'ally',
  'women',
  'underrepresented',
  'racial disparities'],
 ['marginalize',
  'barrier',
  'cisgender',
  'barriers',
  'gender',
  'minority',
  'minorities',
  'heterosexual',
  'marginalized'],
 ['poc', 'ally'],
 ['socioeconomic', 'ally'],
 ['ally'],
 ['barrier',
  'barriers',
  'racial and ethnic',
  'underserved',
  'minority',
  'minorities',
  'socioeconomic',
  'racial'],
 ['diverse background', 'diverse backgrounds', 'ally', 'disability'],
 ['status', 'racial', 'ally'],
 ['barrier', 'barriers', 'pronoun'],
 ['ally'],
 ['ally'],
 ['racial minorities',
  'minority',
  'female',
  'underrepresentation',
  'minorities',
  'racial',
  'underrepresented',
  'ethnic and racial',
  'reparation'],
 ['lack of diversity',
  'historically',
  'advocate',
  'status',
  'inequities',
  'ally',
  'diverse group',
  'equities',
  'advocates',
  'underrepresented',
  'institutional'],
 ['racial and ethnic',
  'political',
  'enhance the diversity',
  'equity',
  'minorities',
  'racial',
  'ally',
  'women',
  'women and underrepresented',
  'underrepresented'],
 ['ally'],
 ['women'],
 ['barrier', 'barriers', 'ally'],
 ['ally'],
 ['biases', 'ally'],
 ['gender', 'disabilities', 'lgbt', 'transgender'],
 ['ally'],
 ['female', 'ally'],
 ['barrier', 'barriers', 'ally'],
 ['ally'],
 ['barrier', 'socioeconomic', 'ally'],
 ['lack of diversity', 'status'],
 ['historically',
  'underserved',
  'minority',
  'diversifying',
  'diversify',
  'socioeconomic',
  'ally',
  'increasing diversity',
  'underrepresented',
  'institutional'],
 ['ally'],
 ['ally'],
 [],
 ['minority',
  'racial',
  'ally',
  'racial disparities',
  'ethnic and racial',
  'biased'],
 ['ally'],
 [],
 ['minority', 'ally', 'biased'],
 ['ally'],
 ['systemic', 'status', 'ally'],
 [],
 [],
 ['ally'],
 ['ally'],
 ['ally'],
 ['barrier', 'systemic', 'systemically', 'ally', 'systemical'],
 [],
 ['pronoun', 'female', 'females'],
 ['ally'],
 ['minority', 'ally', 'diverse group'],
 ['minority', 'racial', 'ally', 'women', 'racial disparity'],
 ['biases', 'ally'],
 ['ally', 'institutional'],
 ['biases',
  'black individuals',
  'racial',
  'ally',
  'women',
  'racial disparities',
  'black individual'],
 ['biases',
  'black individuals',
  'racial',
  'ally',
  'women',
  'racial disparities',
  'black individual'],
 ['systemic', 'ally'],
 ['minority', 'ally', 'inclusion', 'underrepresented'],
 ['underserved', 'ally'],
 [],
 [],
 ['barrier', 'barriers', 'minority', 'ally'],
 ['ally'],
 ['ally'],
 ['poc'],
 ['ally'],
 ['barrier',
  'cisgender',
  'barriers',
  'gender identity',
  'gender',
  'minority',
  'gender minority',
  'ally',
  'gender affirmation',
  'transgender'],
 ['ally'],
 ['ally'],
 ['ally'],
 ['ally'],
 ['ally'],
 ['ally'],
 ['ally'],
 ['ally', 'women'],
 ['segregation',
  'black women',
  'poc',
  'status',
  'inequities',
  'racism',
  'socioeconomic',
  'racial',
  'ally',
  'women',
  'equities',
  'structural racism',
  'institutional',
  'discrimination'],
 ['segregation',
  'black women',
  'poc',
  'status',
  'inequities',
  'racism',
  'socioeconomic',
  'racial',
  'ally',
  'women',
  'equities',
  'structural racism',
  'institutional',
  'discrimination'],
 ['black communities',
  'poc',
  'racial identity',
  'racism',
  'racial',
  'ally',
  'discrimination'],
 ['ally', 'reparation'],
 ['traumatic', 'trauma'],
 ['ethnicity'],
 [],
 ['racial and ethnic', 'minority', 'minorities', 'racial', 'ally'],
 ['ally'],
 ['ally'],
 ['poc', 'reparation'],
 ['diverse individual', 'ally'],
 [],
 ['gender', 'status', 'ethnicity', 'socioeconomic', 'ally'],
 [],
 [],
 ['systemic'],
 ['ally'],
 ['socioeconomic', 'ally'],
 ['ally', 'reparation'],
 ['reparation'],
 ['gender', 'status', 'gender disparities', 'socioeconomic', 'racial'],
 ['ally'],
 [],
 ['poc', 'ally', 'inclusion', 'biased'],
 ['systemic', 'systemically', 'ally', 'disability', 'systemical'],
 ['ally'],
 ['barrier', 'barriers', 'poc', 'ally'],
 ['status'],
 ['poc', 'status', 'ally'],
 ['poc', 'status', 'ally'],
 ['biased'],
 ['systemic', 'minority', 'ally'],
 ['poc', 'ally', 'privilege', 'privileged'],
 ['racial and ethnic', 'racial', 'ally'],
 ['gender', 'ally', 'women'],
 ['disability', 'polarization'],
 ['disability', 'polarization'],
 ['ally'],
 ['ally'],
 ['ally', 'reparation'],
 ['ally'],
 ['status', 'ally'],
 ['female', 'status', 'females', 'ally', 'women'],
 ['ethnicity', 'socioeconomic', 'ally'],
 ['lack of diversity',
  'diverse groups',
  'increase diversity',
  'ally',
  'diverse group',
  'underrepresented',
  'advancing diversity'],
 ['lgbtq+',
  'diverse background',
  'lgbtq',
  'diverse backgrounds',
  'increase diversity',
  'disabilities',
  'minorities',
  'lgbt',
  'ally',
  'women',
  'underrepresented'],
 ['barrier',
  'minority',
  'enhance diversity',
  'inequities',
  'ally',
  'equities',
  'increase the diversity',
  'underrepresented',
  'institutional',
  'advance diversity'],
 ['barrier',
  'barriers',
  'systemic',
  'minority',
  'ethnic minority',
  'advocate',
  'minorities',
  'racial',
  'ally',
  'underrepresented'],
 ['barrier',
  'barriers',
  'racial and ethnic',
  'diverse background',
  'minority',
  'ethnic minority',
  'diverse backgrounds',
  'enhance diversity',
  'minorities',
  'racial',
  'ally',
  'diverse group',
  'promote diversity',
  'underrepresented'],
 ['racially',
  'equity',
  'diversifying',
  'poc',
  'people of color',
  'diversify',
  'racial',
  'ally',
  'bipoc',
  'underrepresented'],
 ['racial and ethnic',
  'racially',
  'minority',
  'inclusive',
  'increase diversity',
  'disabilities',
  'ethnicity',
  'racial',
  'ally',
  'women',
  'underrepresented',
  'disability'],
 ['poc', 'institutional'],
 ['barrier', 'barriers', 'diversified', 'ally'],
 ['barrier', 'barriers', 'ally'],
 ['racially',
  'minority',
  'equity',
  'racial',
  'ally',
  'underrepresented',
  'disability'],
 ['female', 'ally'],
 ['barrier', 'barriers', 'ally'],
 ['ally'],
 ['ally'],
 ['ally'],
 ['poc'],
 ['poc', 'ally'],
 ['barrier',
  'latinx individual',
  'barriers',
  'diverse background',
  'underserved',
  'diverse backgrounds',
  'socioeconomic',
  'ally',
  'latinx individuals'],
 ['systemic', 'ally'],
 ['racial', 'ally', 'racial disparity'],
 ['ally'],
 ['ally'],
 ['ally', 'disability'],
 ['ally'],
 ['barrier'],
 ['ally'],
 ['ally'],
 ['status', 'ally'],
 ['gender',
  'minority',
  'gender minorities',
  'status',
  'minorities',
  'racism',
  'heterosexual',
  'racial',
  'women',
  'structural racism',
  'discrimination',
  'transgender'],
 ['traumatic', 'trauma'],
 ['ally'],
 ['socioeconomic'],
 ['status', 'ally'],
 ['ally', 'disability'],
 ['exclusive', 'ally'],
 ['ally'],
 ['barrier', 'ally'],
 ['ally', 'inclusion', 'biased'],
 ['ally', 'women'],
 [],
 ['barrier',
  'biases',
  'inequity',
  'barriers',
  'equity',
  'racial',
  'ally',
  'equitable',
  'racial disparities'],
 [],
 ['female', 'ally'],
 [],
 ['ally'],
 ['systemic', 'ally'],
 ['systemic', 'ally'],
 ['ally', 'women'],
 ['ally'],
 ['ally'],
 ['ally', 'underrepresented'],
 ['poc', 'ally', 'disability'],
 ['poc', 'ally', 'disability'],
 ['poc', 'ally', 'disability'],
 ['ally'],
 ['socioeconomic', 'ally', 'underrepresented'],
 ['barrier', 'status'],
 ['female', 'poc', 'females', 'ally', 'women'],
 ['segregation',
  'stereotypes',
  'minority',
  'status',
  'racism',
  'socioeconomic',
  'discrimination',
  'stereotype'],
 ['ally'],
 ['barrier', 'ally'],
 ['systemic'],
 ['ally'],
 ['ally'],
 ['ally'],
 ['ally'],
 ['status', 'ally'],
 ['ally'],
 ['ally'],
 ['racial and ethnic',
  'lack of diversity',
  'historically',
  'underserved',
  'racially',
  'racial',
  'ally'],
 ['status', 'ally'],
 ['ally'],
 ['ally'],
 ['ally'],
 ['barrier', 'poc', 'ally'],
 ['racial inequality',
  'social justice',
  'equity',
  'equality',
  'equalities',
  'racism',
  'racial',
  'inequalities',
  'structural racism',
  'disability',
  'racial disparities',
  'inequality'],
 ['ally'],
 ['ally'],
 ['ally'],
 ['sociocultural', 'ally'],
 ['sociocultural', 'ally'],
 ['barrier', 'barriers'],
 [],
 ['poc', 'ally', 'discrimination'],
 ['traumatic', 'ally', 'trauma'],
 ['traumatic',
  'inequities',
  'social inequities',
  'racial',
  'ally',
  'equities',
  'trauma',
  'racial disparities',
  'discrimination'],
 ['gender identity',
  'lgbtq+',
  'gender',
  'minority',
  'lgbtq',
  'gender minority',
  'status',
  'lgbt',
  'discrimination',
  'statuses'],
 ['gender identity',
  'lgbtq+',
  'gender',
  'minority',
  'lgbtq',
  'gender minority',
  'status',
  'lgbt',
  'discrimination',
  'statuses'],
 ['poc'],
 ['status'],
 ['ally'],
 ['ally'],
 ['barrier',
  'barriers',
  'lack of diversity',
  'historically',
  'excluded',
  'equity',
  'inclusive',
  'underrepresentation',
  'diversify',
  'exclusion',
  'ally',
  'underrepresented',
  'institutional',
  'equitable',
  'reparation'],
 ['sociocultural',
  'historically',
  'racially',
  'equity',
  'increase diversity',
  'racial',
  'ally'],
 ['racial and ethnic',
  'racially',
  'minority',
  'ethnic minority',
  'racial',
  'ally',
  'underrepresented'],
 ['black communities',
  'racial',
  'ally',
  'racial disparities',
  'racial disparity'],
 ['underserved', 'people of color', 'ally', 'women'],
 ['ally', 'women'],
 ['disability'],
 ['marginalize',
  'political',
  'historically',
  'black and latinx',
  'racism',
  'racial',
  'ally',
  'structural racism',
  'racial disparities',
  'marginalized'],
 ['ally'],
 ['ally'],
 [],
 ['systemic', 'exclusive', 'ally'],
 ['disability'],
 ['ally'],
 ['historically', 'ally'],
 ['ally', 'underrepresented'],
 ['barrier',
  'barriers',
  'racial and ethnic',
  'historically',
  'minority',
  'excluded',
  'equity',
  'ethnic minority',
  'status',
  'inequities',
  'minorities',
  'racial',
  'ally',
  'equities',
  'reparation'],
 ['ally'],
 ['poc'],
 ['ally'],
 ['ally'],
 ['minority', 'ally'],
 ['ally'],
 ['minorities', 'racial', 'ally', 'underrepresented'],
 ['barrier', 'barriers', 'ally', 'institutional'],
 ['ally'],
 ['disability'],
 ['poc', 'ally'],
 ['ally'],
 ['racial inequalities',
  'racially',
  'equalities',
  'racial',
  'ally',
  'inequalities',
  'racial disparities',
  'discrimination'],
 [],
 ['biases', 'ally'],
 ['ally'],
 ['ally'],
 ['biased'],
 ['ally'],
 ['ally'],
 ['inclusion'],
 [],
 ['racially', 'lgbtq', 'lgbt', 'racial', 'ally'],
 ['ally'],
 ['ally'],
 ['sexual minorities',
  'minorities',
  'heterosexual',
  'ally',
  'underrepresented',
  'disability'],
 ['barrier', 'barriers'],
 ['ally', 'institutional'],
 ['historically',
  'diverse background',
  'racially',
  'minority',
  'diverse backgrounds',
  'dei',
  'diversify',
  'socioeconomic',
  'racial',
  'ally'],
 ['female', 'status', 'females', 'ally', 'women'],
 [],
 [],
 ['barrier',
  'barriers',
  'gender',
  'minority',
  'gender minority',
  'status',
  'inequities',
  'ally',
  'equities',
  'discrimination'],
 ['barrier', 'barriers', 'political', 'ally'],
 ['ally'],
 ['racially', 'female', 'racial', 'ally'],
 ['disability', 'advocacy'],
 [],
 ['ally'],
 ['female', 'poc', 'ally'],
 ['gender', 'ally', 'women', 'inclusion', 'underrepresented'],
 ['ally'],
 [],
 [],
 ['ally'],
 ['ally'],
 ['poc'],
 ['barrier', 'barriers', 'ally'],
 ['biases', 'status', 'socioeconomic', 'women'],
 ['poc', 'ally'],
 ['ally'],

summaries that don't have any flagged words

In [15]:
idx = [i for i, x in enumerate(flagged) if isinstance(x, list) and not x]

In [16]:
no_flagged_terms = df.iloc[idx]
no_flagged_terms

,grant_id,subgrant_id,core_award_number,full_award_number,activity_code,institute_code,subproject_id,current_status,detailed_status,title,...,opportunity_title,opportunity_url,current_total_obligated,post_termination_deobligation,award_value,award_outlaid,award_remaining,reporter_url,usaspending_url,taggs_url
0,AA007459,NaN,T32AA007459,5T32AA007459-40,T32,AA,NaN,Restored,Unfrozen (confirmed),Alcohol Intervention Treatment Outcome Researc...,...,Ruth L. Kirschstein National Research Service ...,https://grants.nih.gov/grants/guide/pa-files/P...,8903933.00,NaN,8903933.00,2021558.65,6882374.35,https://reporter.nih.gov/project-details/11098673,https://www.usaspending.gov/award/ASST_NON_T32...,NaN
18,AA029033,NaN,R21AA029033,NaN,R21,AA,NaN,Restored,Unfrozen (confirmed),NaN,...,NaN,NaN,439344.12,NaN,439344.12,438066.63,1277.49,NaN,https://www.usaspending.gov/award/ASST_NON_R21...,NaN
20,AA029044,04S1,R01AA029044,3R01AA029044-04S1,R01,AA,NaN,Disrupted,Terminated,Intersectional Approaches to Population-Level ...,...,Accelerating the Pace of Drug Abuse Research U...,https://grants.nih.gov/grants/guide/pa-files/P...,NaN,NaN,NaN,NaN,NaN,https://reporter.nih.gov/project-details/11160901,https://www.usaspending.gov/award/ASST_NON_R01...,NaN
25,AA029180,NaN,R00AA029180,5R00AA029180-05,R00,AA,NaN,Restored,Unfrozen (confirmed),Corticolimbic Neuroimmune Determinants of Soci...,...,NIH Pathway to Independence Award (Parent K99/...,https://grants.nih.gov/grants/guide/pa-files/P...,1138465.00,NaN,1138465.00,939517.30,198947.70,https://reporter.nih.gov/project-details/11158870,https://www.usaspending.gov/award/ASST_NON_R00...,NaN
59,AA031213,NaN,R01AA031213,5R01AA031213-03,R01,AA,NaN,Restored,Reinstated (confirmed),The Impact of Stress on Alcohol-Related Sexual...,...,NIH Research Project Grant (Parent R01 Clinica...,https://grants.nih.gov/grants/guide/pa-files/P...,1671954.00,NaN,1671954.00,689957.48,981996.52,https://reporter.nih.gov/project-details/11369221,https://www.usaspending.gov/award/ASST_NON_R01...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5246,NS128148,NaN,UG3NS128148,1UG3NS128148-01A1,UG3,NS,NaN,Restored,Reinstated (confirmed),Peripherally-restricted non-addictive cannabin...,...,HEAL Initiative: Non-addictive Analgesic Thera...,https://grants.nih.gov/grants/guide/pa-files/R...,3174343.00,NaN,3174343.00,2765310.19,409032.81,https://reporter.nih.gov/project-details/10726405,https://www.usaspending.gov/award/ASST_NON_UG3...,NaN
5256,NS128947,NaN,R01NS128947,4R01NS128947-02,R01,NS,NaN,Restored,Unfrozen (unconfirmed),High-Speed Imaging of Cortical and White Matte...,...,Selectively Target Technology Development to U...,https://grants.nih.gov/grants/guide/pa-files/P...,3087726.00,NaN,3087726.00,2504171.37,583554.63,https://reporter.nih.gov/project-details/10699914,https://www.usaspending.gov/award/ASST_NON_R01...,NaN
5263,NS129589,NaN,F32NS129589,5F32NS129589-03,F32,NS,NaN,Restored,Reinstated (confirmed),The Role of Mechanosensory Activity in the Tra...,...,NINDS Ruth L. Kirschstein National Research Se...,https://grants.nih.gov/grants/guide/pa-files/P...,221404.00,NaN,221404.00,189479.56,31924.44,https://reporter.nih.gov/project-details/11017698,https://www.usaspending.gov/award/ASST_NON_F32...,NaN
5275,NS130475,NaN,R21NS130475,NaN,R21,NS,NaN,Restored,Unfrozen (confirmed),Recognition of Shape by Vision and Touch,...,NaN,NaN,438625.00,NaN,438625.00,436212.61,2412.39,NaN,https://www.usaspending.gov/award/ASST_NON_R21...,https://taggs.hhs.gov/Detail/AwardDetail?arg_A...
5279,NS130838,NaN,R01NS130838,5R01NS130838-03,R01,NS,NaN,Restored,Unfrozen (confirmed),Development of Culturally Appropriate Spanish ...,...,NIH Research Project Grant (Parent R01 Clinica...,https://grants.nih.gov/grants/guide/pa-files/P...,1894593.00,NaN,1894593.00,869096.50,1025496.50,https://reporter.nih.gov/project-details/11243551,https://www.usaspending.gov/award/ASST_NON_R01...,NaN

In [17]:
no_flagged_terms[['grant_id','detailed_status','title','frozen_date','unfrozen_date','project_start','project_end','abstract','terms','org_name','usaspending_url']].to_csv('./data/no_flagged_terms.csv', index=False)

In [18]:
no_flagged_terms

,grant_id,subgrant_id,core_award_number,full_award_number,activity_code,institute_code,subproject_id,current_status,detailed_status,title,...,opportunity_title,opportunity_url,current_total_obligated,post_termination_deobligation,award_value,award_outlaid,award_remaining,reporter_url,usaspending_url,taggs_url
0,AA007459,NaN,T32AA007459,5T32AA007459-40,T32,AA,NaN,Restored,Unfrozen (confirmed),Alcohol Intervention Treatment Outcome Researc...,...,Ruth L. Kirschstein National Research Service ...,https://grants.nih.gov/grants/guide/pa-files/P...,8903933.00,NaN,8903933.00,2021558.65,6882374.35,https://reporter.nih.gov/project-details/11098673,https://www.usaspending.gov/award/ASST_NON_T32...,NaN
18,AA029033,NaN,R21AA029033,NaN,R21,AA,NaN,Restored,Unfrozen (confirmed),NaN,...,NaN,NaN,439344.12,NaN,439344.12,438066.63,1277.49,NaN,https://www.usaspending.gov/award/ASST_NON_R21...,NaN
20,AA029044,04S1,R01AA029044,3R01AA029044-04S1,R01,AA,NaN,Disrupted,Terminated,Intersectional Approaches to Population-Level ...,...,Accelerating the Pace of Drug Abuse Research U...,https://grants.nih.gov/grants/guide/pa-files/P...,NaN,NaN,NaN,NaN,NaN,https://reporter.nih.gov/project-details/11160901,https://www.usaspending.gov/award/ASST_NON_R01...,NaN
25,AA029180,NaN,R00AA029180,5R00AA029180-05,R00,AA,NaN,Restored,Unfrozen (confirmed),Corticolimbic Neuroimmune Determinants of Soci...,...,NIH Pathway to Independence Award (Parent K99/...,https://grants.nih.gov/grants/guide/pa-files/P...,1138465.00,NaN,1138465.00,939517.30,198947.70,https://reporter.nih.gov/project-details/11158870,https://www.usaspending.gov/award/ASST_NON_R00...,NaN
59,AA031213,NaN,R01AA031213,5R01AA031213-03,R01,AA,NaN,Restored,Reinstated (confirmed),The Impact of Stress on Alcohol-Related Sexual...,...,NIH Research Project Grant (Parent R01 Clinica...,https://grants.nih.gov/grants/guide/pa-files/P...,1671954.00,NaN,1671954.00,689957.48,981996.52,https://reporter.nih.gov/project-details/11369221,https://www.usaspending.gov/award/ASST_NON_R01...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5246,NS128148,NaN,UG3NS128148,1UG3NS128148-01A1,UG3,NS,NaN,Restored,Reinstated (confirmed),Peripherally-restricted non-addictive cannabin...,...,HEAL Initiative: Non-addictive Analgesic Thera...,https://grants.nih.gov/grants/guide/pa-files/R...,3174343.00,NaN,3174343.00,2765310.19,409032.81,https://reporter.nih.gov/project-details/10726405,https://www.usaspending.gov/award/ASST_NON_UG3...,NaN
5256,NS128947,NaN,R01NS128947,4R01NS128947-02,R01,NS,NaN,Restored,Unfrozen (unconfirmed),High-Speed Imaging of Cortical and White Matte...,...,Selectively Target Technology Development to U...,https://grants.nih.gov/grants/guide/pa-files/P...,3087726.00,NaN,3087726.00,2504171.37,583554.63,https://reporter.nih.gov/project-details/10699914,https://www.usaspending.gov/award/ASST_NON_R01...,NaN
5263,NS129589,NaN,F32NS129589,5F32NS129589-03,F32,NS,NaN,Restored,Reinstated (confirmed),The Role of Mechanosensory Activity in the Tra...,...,NINDS Ruth L. Kirschstein National Research Se...,https://grants.nih.gov/grants/guide/pa-files/P...,221404.00,NaN,221404.00,189479.56,31924.44,https://reporter.nih.gov/project-details/11017698,https://www.usaspending.gov/award/ASST_NON_F32...,NaN
5275,NS130475,NaN,R21NS130475,NaN,R21,NS,NaN,Restored,Unfrozen (confirmed),Recognition of Shape by Vision and Touch,...,NaN,NaN,438625.00,NaN,438625.00,436212.61,2412.39,NaN,https://www.usaspending.gov/award/ASST_NON_R21...,https://taggs.hhs.gov/Detail/AwardDetail?arg_A...
5279,NS130838,NaN,R01NS130838,5R01NS130838-03,R01,NS,NaN,Restored,Unfrozen (confirmed),Development of Culturally Appropriate Spanish ...,...,NIH Research Project Grant (Parent R01 Clinica...,https://grants.nih.gov/grants/guide/pa-files/P...,1894593.00,NaN,1894593.00,869096.50,1025496.50,https://reporter.nih.gov/project-details/11243551,https://www.usaspending.gov/award/ASST_NON_R01...,NaN

Find which terms are flagged per each description

In [19]:
pd.set_option('display.max_colwidth', None)

In [20]:
print(no_flagged_terms[no_flagged_terms['grant_id']=='AG088233']['abstract'].to_string())

527    Abstract. Currently there are limited therapeutic treatments to slow, prevent, or cure neurodegenerative diseases such as Alzheimer’s Disease or Alzheimer’s-related Dementias. Instead, most therapies rely on managing symptoms. These neurodegenerative diseases are characterized by accumulation of intrinsically disordered proteins (IDPs) and impairment of proteasome-mediated protein degradation. This R36 proposal aims to investigate small molecule 20S proteasome activation as a novel strategy to resolve both pathogenic events. Our group has identified fluspirilene and N-acyl-fluspirilene as a novel class of small molecules that not only activate the 20S proteasome to degrade IDPs, but also overcome IDP-induced proteasome impairment. The overarching aims of this project are to (1) identify the mechanism by which the N-acyl-fluspirilene class selectively enhances 20S proteasome activity, and (2) develop enhanced small molecule activators of the 20S proteasome. Successful completion of this work will enable the rapid design, development, and identification of 20S proteasome activators, and elucidate the role of 20S proteasome modulation in neurodegenerative diseases as a novel therapeutic strategy for disease treatment.

From HHS website

In [28]:
import camelot

/Users/elena/Documents/GitHub/nih-terminations/.venv/lib/python3.8/site-packages/pypdf/_crypt_providers/_cryptography.py:32: CryptographyDeprecationWarning: ARC4 has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.ARC4 and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 48.0.0.
  from cryptography.hazmat.primitives.ciphers.algorithms import AES, ARC4

In [62]:
df_hhs = camelot.read_pdf("data/HHS_Grants_Terminated.pdf",strip_text='\n')[0].df

df_hhs.columns = df_hhs.iloc[0]
df_hhs = df_hhs[1:].reset_index(drop=True)

In [65]:
df_hhs.head()

,OPDIV,FAIN,Obligation Document Numbers,Recipient Name,Recipient State,Country,Action Date (Date Terminated),Total Amount Obligated,Total Amount Expended,Total Payment Amount (As of Termination),Unliquidated Obligations (As of Termination),Award Title,Presidential Action,For Cause (Put X if applicable)
0,ACF,2301CAPREP,2301CAPREP,"PUBLIC HEALTH, CALIFORNIA DEPARTMENT OF",CALIFORNIA,UNITED STATES,8/21/2025,"$5,828,427.00","$4,287,562.14","$4,287,562.14","$1,540,864.86",PREP-2023,Termination for Cause,X
1,ACF,2401CAPREP,2401CAPREP,"PUBLIC HEALTH, CALIFORNIA DEPARTMENT OF",CALIFORNIA,UNITED STATES,8/21/2025,"$6,217,050.00",-,-,"$6,217,050.00",PREP-2024,Termination for Cause,X
2,ACF,2501CAPREP,2501CAPREP,"PUBLIC HEALTH, CALIFORNIA DEPARTMENT OF",CALIFORNIA,UNITED STATES,8/21/2025,"$6,148,951.00",-,-,"$6,148,951.00",PREP-2025,Termination for Cause,X
3,ACF,90CA1896,90CA189601,AMERICAN BAR ASSOCIATION,DISTRICT OF COLUMBIA,UNITED STATES,2/20/2025,"$500,000.00","$99,362.99","$99,362.99","$400,637.01",MICHIGAN STOP OVERREPORTING OUR PEOPLE (MI STOP),Termination for Cause,X
4,ACF,90CT7016,90CT701603,"NORTH AMERICAN COUNCIL ON ADOPTABLE CHILDREN, INC",Minnesota,UNITED STATES,12/8/2025,"$10,000,000.00","$2,557,706.02","$2,557,706.02","$7,442,293.98",Child Welfare Workforce Institute,Departmental Authority,-

Use FAIN to identify grants on website

In [118]:
import requests
import json

def search_fain(fain):
    url = f"https://api.usaspending.gov/api/v2/search/spending_by_award/"
    
    payload = {
        "filters": {
            "award_type_codes": ["02", "03", "04", "05"],
            "award_ids": [fain]
        },
        "fields": [
            "Award ID",
            "Recipient Name",
            "Award Amount",
            "Description"
        ],
    }

    r = requests.post(url, json=payload)
    r.raise_for_status()

    url = f"https://api.usaspending.gov/api/v2/awards/{json.loads(json.dumps(r.json(), indent=2))['results'][0]['internal_id']}/"

    r = requests.get(url)
    r.raise_for_status()
    return json.loads(json.dumps(r.json(), indent=2))['cfda_info'][0]['cfda_objectives']

fain = '2301CAPREP'
results = search_fain(fain)
print(results)

The purpose of this program is to support projects that educate youth between 10 and 19 years of age and pregnant and parenting youth under age 21 on abstinence and contraception for the prevention of pregnancy and sexually transmitted infections (STIs), including human immunodeficiency virus (HIV) and acquired immunodeficiency syndrome (AIDS). Funds will support the implementation of projects that replicate evidence-based, effective programs, or substantially incorporate elements of effective programs that have been proven, on the basis of rigorous scientific research to change behavior, which means delaying sexual activity, increasing condom or contraceptive use for sexually active youth, or reducing pregnancy among youth. Projects are further required to incorporate at least three of six adulthood preparation subjects, to include healthy life skills, adolescent development, parent-child communication, financial literacy, educational and career success, and healthy relationships.

The overall goal of the Competitive PREP program is to educate adolescents on both abstinence and contraception for the prevention of pregnancy and STIs, including HIV/AIDS. The following are objectives of the Competitive PREP program:
1.	Replicate evidence-based effective programs or incorporate elements of effective programs that are proven to change behaviors, including delaying sexual activity, increasing condom and contraceptive use for sexually active youth, or reducing pregnancy among youth;
2.	Implement curricula that includes medically accurate information (referenced in peer-reviewed publications by educational, scientific, governmental, or health organizations) and is age-appropriate, culturally appropriate, and inclusive;
3.	Promote successful and healthy transition to adulthood through the implementation of at least three of six adulthood preparation subjects; and
4.	Target prevention education to youth between the ages of 10 and 19, or pregnant and parenting youth under 21 years of age, who are at high-risk for becoming pregnant or who have special circumstances.

In [119]:
df_hhs['description'] = df_hhs.apply(lambda i: search_fain(i['FAIN']), axis=1)

In [120]:
df_hhs

,OPDIV,FAIN,Obligation Document Numbers,Recipient Name,Recipient State,Country,Action Date (Date Terminated),Total Amount Obligated,Total Amount Expended,Total Payment Amount (As of Termination),Unliquidated Obligations (As of Termination),Award Title,Presidential Action,For Cause (Put X if applicable),description
0,ACF,2301CAPREP,2301CAPREP,"PUBLIC HEALTH, CALIFORNIA DEPARTMENT OF",CALIFORNIA,UNITED STATES,8/21/2025,"$5,828,427.00","$4,287,562.14","$4,287,562.14","$1,540,864.86",PREP-2023,Termination for Cause,X,"The purpose of this program is to support projects that educate youth between 10 and 19 years of age and pregnant and parenting youth under age 21 on abstinence and contraception for the prevention of pregnancy and sexually transmitted infections (STIs), including human immunodeficiency virus (HIV) and acquired immunodeficiency syndrome (AIDS). Funds will support the implementation of projects that replicate evidence-based, effective programs, or substantially incorporate elements of effective programs that have been proven, on the basis of rigorous scientific research to change behavior, which means delaying sexual activity, increasing condom or contraceptive use for sexually active youth, or reducing pregnancy among youth. Projects are further required to incorporate at least three of six adulthood preparation subjects, to include healthy life skills, adolescent development, parent-child communication, financial literacy, educational and career success, and healthy relationships.\n\nThe overall goal of the Competitive PREP program is to educate adolescents on both abstinence and contraception for the prevention of pregnancy and STIs, including HIV/AIDS. The following are objectives of the Competitive PREP program: \n1.\tReplicate evidence-based effective programs or incorporate elements of effective programs that are proven to change behaviors, including delaying sexual activity, increasing condom and contraceptive use for sexually active youth, or reducing pregnancy among youth; \n2.\tImplement curricula that includes medically accurate information (referenced in peer-reviewed publications by educational, scientific, governmental, or health organizations) and is age-appropriate, culturally appropriate, and inclusive; \n3.\tPromote successful and healthy transition to adulthood through the implementation of at least three of six adulthood preparation subjects; and \n4.\tTarget prevention education to youth between the ages of 10 and 19, or pregnant and parenting youth under 21 years of age, who are at high-risk for becoming pregnant or who have special circumstances."
1,ACF,2401CAPREP,2401CAPREP,"PUBLIC HEALTH, CALIFORNIA DEPARTMENT OF",CALIFORNIA,UNITED STATES,8/21/2025,"$6,217,050.00",-,-,"$6,217,050.00",PREP-2024,Termination for Cause,X,"The purpose of this program is to support projects that educate youth between 10 and 19 years of age and pregnant and parenting youth under age 21 on abstinence and contraception for the prevention of pregnancy and sexually transmitted infections (STIs), including human immunodeficiency virus (HIV) and acquired immunodeficiency syndrome (AIDS). Funds will support the implementation of projects that replicate evidence-based, effective programs, or substantially incorporate elements of effective programs that have been proven, on the basis of rigorous scientific research to change behavior, which means delaying sexual activity, increasing condom or contraceptive use for sexually active youth, or reducing pregnancy among youth. Projects are further required to incorporate at least three of six adulthood preparation subjects, to include healthy life skills, adolescent development, parent-child communication, financial literacy, educational and career success, and healthy relationships.\n\nThe overall goal of the Competitive PREP program is to educate adolescents on both abstinence and contraception for the prevention of pregnancy and STIs, including HIV/AIDS. The following are objectives of the Competitive PREP program: \n1.\tReplicate evidence-based effective programs or incorporate elements of effective programs that are proven to change behaviors, including delaying sexual activity, increasing condom and contraceptive use for sexually active youth, or reducing pregnancy among youth; \n2.\tImplement curricula that includes medically accurate information (referenced in peer-reviewed publications by educational, scientific, governmental, or health organizations) and is age-appropriate, culturally appropriate, and inclusive; \n3.\tPromote successful and healthy transition to adulthood through the implementation of at least three of six adulthood preparation subjects; and \n4.\tTarget prevention education to youth between the ages of 10 and 19, or pregnant and parenting youth under 21 years of age, who are at high-risk for becoming pregnant or who have special circumstances."
2,ACF,2501CAPREP,2501CAPREP,"PUBLIC HEALTH, CALIFORNIA DEPARTMENT OF",CALIFORNIA,UNITED STATES,8/21/2025,"$6,148,951.00",-,-,"$6,148,951.00",PREP-2025,Termination for Cause,X,"The purpose of this program is to support projects that educate youth between 10 and 19 years of age and pregnant and parenting youth under age 21 on abstinence and contraception for the prevention of pregnancy and sexually transmitted infections (STIs), including human immunodeficiency virus (HIV) and acquired immunodeficiency syndrome (AIDS). Funds will support the implementation of projects that replicate evidence-based, effective programs, or substantially incorporate elements of effective programs that have been proven, on the basis of rigorous scientific research to change behavior, which means delaying sexual activity, increasing condom or contraceptive use for sexually active youth, or reducing pregnancy among youth. Projects are further required to incorporate at least three of six adulthood preparation subjects, to include healthy life skills, adolescent development, parent-child communication, financial literacy, educational and career success, and healthy relationships.\n\nThe overall goal of the Competitive PREP program is to educate adolescents on both abstinence and contraception for the prevention of pregnancy and STIs, including HIV/AIDS. The following are objectives of the Competitive PREP program: \n1.\tReplicate evidence-based effective programs or incorporate elements of effective programs that are proven to change behaviors, including delaying sexual activity, increasing condom and contraceptive use for sexually active youth, or reducing pregnancy among youth; \n2.\tImplement curricula that includes medically accurate information (referenced in peer-reviewed publications by educational, scientific, governmental, or health organizations) and is age-appropriate, culturally appropriate, and inclusive; \n3.\tPromote successful and healthy transition to adulthood through the implementation of at least three of six adulthood preparation subjects; and \n4.\tTarget prevention education to youth between the ages of 10 and 19, or pregnant and parenting youth under 21 years of age, who are at high-risk for becoming pregnant or who have special circumstances."
3,ACF,90CA1896,90CA189601,AMERICAN BAR ASSOCIATION,DISTRICT OF COLUMBIA,UNITED STATES,2/20/2025,"$500,000.00","$99,362.99","$99,362.99","$400,637.01",MICHIGAN STOP OVERREPORTING OUR PEOPLE (MI STOP),Termination for Cause,X,"To improve the national, state, and community activities for the prevention, assessment, identification, and treatment of child abuse and neglect through research, demonstration, service improvement, evaluation of best practices, dissemination of information, and technical assistance."
4,ACF,90CT7016,90CT701603,"NORTH AMERICAN COUNCIL ON ADOPTABLE CHILDREN, INC",Minnesota,UNITED STATES,12/8/2025,"$10,000,000.00","$2,557,706.02","$2,557,706.02","$7,442,293.98",Child Welfare Workforce Institute,Departmental Authority,-,"This program supports research and demonstration projects which are of national or regional significance and special projects for the demonstration of new methods which show promise of substantial contribution to the advancement of child welfare. Projects are intended to demonstrate the utilization of research in the field of child welfare to encourage experimental and special types of child welfare services, and provide professional education opportunities to prospective and current child welfare agency staff and to develop competency-based training curricula and special projects for training child welfare personnel in specific areas."
5,ACF,90PH0032,90PH003203,"CHILD TRENDS, INC",District of Columbia,UNITED STATES,12/8/2025,"$3,000,000.00","$566,271.24","$566,271.24","$2,433,728.76",Center for Research on Hispanic Children and Families,Departmental Authority,-,"The Child Care and Development Fund (CCDF) is the primary federal funding source to help certain families with low incomes access child care and to improve the quality of child care for all children. As a block grant, CCDF gives funding to States, Territories, and Tribes to provide child care subsidies primarily through vouchers or certificates to families with low income. In addition, CCDF funds are used to improve the quality of child care for both subsidized and unsubsidized children. CCDF consists of both Discretionary funding authorized by the Child Care and Development Block Grant (CCDBG) Act and Mandatory and Matching funding under the Social Security Act. \nIn addition to the block grants to States, Territories and Tribes, a small portion of the CCDF is used by the Office of Child Care to provide technical assistance to lead agencies on administering the program. A small portion of CCDF is also used for child care research, demonstration and evaluation, and federal administration activities."
6,ACF,90YE0293,90YE029304,URBAN INSTITUTE (THE),District of Columbia,UNITED STATES,12/8/2025,"$8,782,966.00","$4,894,844.58","$4,894,844.58","$3,888,121.42",Center to Support Research and Evaluation Capacity of CCDF Lead Agencies,Departmental Authority,-,"The Child Care and Development Fund (CCDF) is the primary federal funding source to help certain families with low incomes access child care and to improve the quality of child care for all children. As a block grant, CCDF gives funding to States, Territories, and Tribes to provide child care subsidies primarily through vouchers or certificates to families with low income. In addition, CCDF funds are used to improve the quality of child care for both subsidized and unsubsidized children. CCDF consists of both Discretionary funding authorized by the Child Care and Development Block Grant (CCDBG) Act and Mandatory and Matching funding under the Social Security Act. \nIn addition to the block grants to States, Territories and Tribes, a small portion of the CCDF is used by the Office of Child Care to provide technical assistance to lead agencies on administering the program. A small portion of CCDF is also used for child care research, demonstration and evaluation, and federal administration activities."
7,ACF,90YE0318,90YE031801,NORTHWESTERN UNIVERSITY,ILLINOIS,UNITED STATES,7/8/2025,"$25,000.00",-,-,"$25,000.00",A QUALITATIVE EVALUATION OF EQUITABLE ACCESS AND PARTICIPATION IN UNIVERSAL PRE-KINDERGARTEN,Termination for Cause,X,"The Mandatory and Matching portion (or Child Care Entitlement or CCE) of the Child Care and Development Fund (CCDF) program consists of three formula grant programs and one program grant. The purpose of the three formula grants funds is to help certain families with low incomes access child care and to improve the quality of child care for all children. The Mandatory and Matching funds are made available in section 418 of the Social Security Act (42 U.S.C. 618) and are not subject to annual appropriations. \nThe first formula grant program is formula grants to States and DC. These include \nMandatory funds (which are 100% federal) and Matching funds (which require a State match and maintenance of effort). Allocations of the Mandatory Funds are based on a State's Federal share of the expenditures for the now-repealed AFDC-linked child care programs (AFDC/JOBS Child Care, Transitional Child Care, and At-Risk Child Care) in 1994 or 1995, or the average of 1992 through 1994, whichever was greater. A State is not required to expend any State funds in order to receive its share of the Mandatory Funds. \nMatching funds are available to states if three conditions are met by the end of the fiscal year in which the funds are awarded: (1) all Mandatory funds are obligated; (2) the stateâ€™s Maintenance-of-Effort funds are expended; and (3) the state provides its share of Matching funds at the FMAP rate. The Matching Funds are distributed based on the number of children under age 13 in a State compared with the national total of children under age 13. \nThe second formula grant is Mandatory funds to territories, including American Samoa, Guam, Puerto Rico, the Commonwealth of the Northern Mariana Islands, and the Virgin Islands of the United States. Territory Mandatory funds are allotted based on the number of children under age five living in territories and per capita income in the territories. Territory Mandatory funds are not subject to any matching requirements. Each year, Territories receive $75 million in Mandatory funding. Territory Mandatory funds must be obligated in the fiscal year that they are awarded and liquidated in the following year; however, in certain circumstances, unobligated funds may be reobligated in subsequent fiscal years. \n\nThe third formula grant is Mandatory funds to Tribal Lead Agencies. Tribal Mandatory funds are not subject to any matching requirements. Each year, Tribal Lead Agencies receive $100 million in Tribal Mandatory funds. Mandatory funds to Tribes are allocated based on the number of children under the age of 13 in a Tribeâ€™s service area. Lastly, in addition to the block grants to States, Territories and Tribes, a small program grant is used by the Office of Child Care to provide technical assistance to lead agencies on administering the program. A small portion of CCDF is also used for child care research, demonstration and evaluation activities."
8,ACF,90YE0329,90YE032901,UNIVERSITY OF TENNESSEE,TENNESSEE,UNITED STATES,7/8/2025,"$99,999.00","$5,716.46","$5,716.46","$94,282.54",EXAMINING THE EVOLUTION OF MENTAL HEALTH AMONG RACIAL MINORITY EARLY CARE AND EDUCATION WORKFORCE FROM 2019 TO THE COVID-19 PANDEMIC: A LATENT GROWTH MODELING APPROACH,Termination for Cause,X,"The Mandatory and Matching portion (or Child Care Entitlement or CCE) of the Child Care and Development Fund (CCDF) program consists of three formula grant programs and one program grant. The purpose of the three formula grants funds is to help certain families with low incomes access child care and to improve the quality of child care for all children. The Mandatory and Matching funds are made available in section 418 of the Social Security Act (42 U.S.C. 618) and are not subject to annual appropriations. \nThe first formula grant program is formula grants to States and DC. These include \nMandatory funds (which are 100% federal) and Matching funds (which require a State match and maintenance of effort). Allocations of the Mandatory Funds are based on a State's Federal share of the expenditures for the now-repealed AFDC-linked child care programs (AFDC/JOBS Child Care, Transitional Child Care, and At-Risk Child Care) in 1994 or 1995, or the average of 1992 through 1994, whichever was greater. A State is not required to expend any State funds in order to receive its share of the Mandatory Funds. \nMatching funds are available to states if three conditions are met by the end of the fiscal year in which the funds are awarded: (1) all Mandatory funds are obligated; (2) the stateâ€™s Maintenance-of-Effort funds are expended; and (3) the state provides its share of Matching funds at the FMAP rate. The Matching Funds are distributed based on the number of children under age 13 in a State compared with the national total of children under age 13. \nThe second formula grant is Mandatory funds to territories, including American Samoa, Guam, Puerto Rico, the Commonwealth of the Northern Mariana Islands, and the Virgin Islands of the United States. Territory Mandatory funds are allotted based on the number of children under age five living in territories and per capita income in the territories. Territory Mandatory funds are not subject to any matching requirements. Each year, Territories receive $75 million in Mandatory funding. Territory Mandatory funds must be obligated in the fiscal year that they are awarded and liquidated in the following year; however, in certain circumstances, unobligated funds may be reobligated in subsequent fiscal years. \n\nThe third formula grant is Mandatory funds to Tribal Lead Agencies. Tribal Mandatory funds are not subject to any matching requirements. Each year, Tribal Lead Agencies receive $100 million in Tribal Mandatory funds. Mandatory funds to Tribes are allocated based on the number of children under the age of 13 in a Tribeâ€™s service area. Lastly, in addition to the block grants to States, Territories and Tribes, a small program grant is used by the Office of Child Care to provide technical assistance to lead agencies on administering the program. A small portion of CCDF is also used for child care research, demonstration and evaluation activities."